single_actor_batch=1
target_error=0.05
iterations=1000
max_time=100
report_details=1
scale_only=intellect,crit,mastery,vers,haste
calculate_scale_factors=0
# profileset_metric=dps/:prioritydps
log=1
ptr=1
desired_targets=1

mage="Base"
source=default
spec=fire
level=90
race=orc
role=spell
position=back
talents=C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sssMDAwmZmx2YmZGAAAAAgNzMzMDAAGzwYmZmZ2GAmZImxYwMMA

actions=fireball

# Executed before combat begins. Accepts non-harmful actions only.
head=voidbreakers_veil,id=250060,bonus_id=12214/12667/12497,ilevel=289,gem_id=240967
neck=eternal_voidsong_chain,id=249368,bonus_id=12792/13448/13452,ilevel=289,gem_id=240890
shoulders=voidbreakers_leyline_nexi,id=250058,bonus_id=40/12675/12806/13335/13340,ilevel=289,enchant_id=7973
back=voidbreakers_encryption,id=250055,bonus_id=40/12806/13335,ilevel=289
chest=robes_of_endless_oblivion,id=249912,bonus_id=40/12676/12806/13335/13336,ilevel=289,enchant_id=7987
wrists=
hands=voidbreakers_gloves,id=250061,bonus_id=40/12675/12806/13335/13337,ilevel=289
waist=whisperinscribed_sash,id=249376,ilevel=289,gem_id=240900
legs=voidbreakers_britches,id=250059,bonus_id=40/12676/12806/13335/13339,ilevel=289,enchant_id=7935
feet=voidbreakers_treads,id=250062,bonus_id=40/12806/13335,ilevel=289,enchant_id=8019
finger1=
finger2=omission_of_light,id=251093,bonus_id=40/12806/13335/13534,ilevel=289,gem_id=240916,enchant_id=7969
trinket1=
trinket2=
main_hand=

copy="Ribbon"
trinket1=locuswalkers_ribbon,id=249809,bonus_id=40/12806/13440,ilevel=289





# copy="Frostfire"
# talents=C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAmZZGzMLzCEAAwiZmx2YmZGAAAAAgNzMzMDAAGzYmZmZmZ2AmZADzYMYwA

# copy="Sunfury Cinderella"
# talents=C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sssMDAwmZmZ2GGzMAAAAAgNzMzMDAAGmZGzMMz2AwMDxMGGmhB

# copy="Sunfury Pyroclasm"
# talents=C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sstMDAwmZmx2MzMzMAAAAAgNzMzMDAAmxYmZmxMzGAmZImxAGMA

# copy="Sunfury Burnout no Scorch"
# talents=C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sssMDAwmZmx2YmZmHAAAAAAsZmZmZAAwYGzYmZmZ2AwMDxMGDGMA

# copy="Sunfury Burnout BZ"
# talents=C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sssMDAwmZmx2YmZGAAAAAgNzMzMDAAGzYmZmZmZ2AwMDxMGDGMA

# copy="Sunfury Burnout Scorch"
# talents=C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sssMDAwmZmx2YmZGAAAAAgNzMzMDAAGzwYmZmZ2GAmZImxYwMMA