#!/usr/bin/env python

import sys

__max_tiers = 6
__talents_per_tier = 3
__class_map = {
    'Death_Knight': [
        (0, -1),    # 56: All
                    # 57: None
                    # 58: None
                    # 60: Death Pact, Death Siphon (tank only, and we dont teset tanks atm)
        (4, -1),    # 75: All
                    # 90: None
    ],
    'Druid': [
        (0, 3),     # 15: Wild Charge
        (1, -1),    # 30: All
        (2, 3),     # 45: Typhoon
        (3, -1),    # 60: All
                    # 75: None
        (5, -1),    # 90: All
    ],
    'Hunter': [
                    # 15: None
                    # 30: None
        (2, 2),     # 45: Aspect of the Iron Hawk
        (3, -1),    # 60: All
        (4, -1),    # 75: All
        (5, -1),    # 90: All
    ],
    'Mage': [
        (0, 1), (0, 2), # 15: Presence of Mind, Ice Floes
                        # 30: None
                        # 45: None
        (3, 3),         # 60: Cold Snap
        (4, -1),        # 75: All
        (5, -1),        # 90: All
    ],
    'Monk': [
                        # 15: None
        (1, -1),        # 30: All
        (2, -1),        # 45: All
                        # 60: None
                        # 75: None
        (5, -1),        # 90: All
    ],
    'Paladin': [
                        # 15: None
                        # 30: None
        (2, -1),        # 45: All
        (3, -1),        # 60: All
        (4, -1),        # 75: All
        (5, -1),        # 90: All
    ],
    'Priest': [
                        # 15: None
                        # 30: None
        (2, -1),        # 45: All
                        # 60: Desperate Prayer is defined, but not included in (default) action lists, so None
        (4, -1),        # 75: All
        (5, -1),        # 90: All
    ],
    'Rogue': [
        (0, -1),        # 15: All
                        # 30: None
                        # 45: None
                        # 60: None
                        # 75: None
        (5, -1),        # 90: All
    ],
    'Shaman': [
                        # 15: None
                        # 30: None
                        # 45: None
        (3, -1),        # 60: All
                        # 75: None
        (5, -1),        # 90: All
    ],
    'Warlock': [
        (0, 2),         # 15: Soul Leech
        (1, 2),         # 30: Mortal Coil
        (2, 1),         # 45: Soul Link
                        # 60: None
        (4, -1),        # 75: All
        (5, -1),        # 90: All
    ],
    'Warrior': [
        (0, 1),         # 15: Juggernaut
        (1, 2), (1, 3), # 30: Second Wind, Impending Victory
                        # 45: None
        (3, -1),        # 60: All
                        # 75: None
        (5, -1),        # 90: All
    ]
}

if len(sys.argv) < 2:
    sys.exit(1)

_class = None
for class_name in __class_map.keys():
    if class_name in sys.argv[1]:
        _class = class_name
        break

if not _class:
    sys.exit(1)

# Check untalented
combinations = [ '0' * __max_tiers ]

for talents in __class_map[_class]:
    talent_arr = [ '0' ] * __max_tiers
    if talents[1] == -1:
        for talent in xrange(0, __talents_per_tier):
            talent_arr[talents[0]] = str(talent + 1)
            talent_str = ''.join(talent_arr)

            if talent_str not in combinations:
                combinations.append(talent_str)
    else:
        talent_arr[talents[0]] = str(talents[1])
        combinations.append(''.join(talent_arr))

print ' '.join(combinations)

sys.exit(0)

