# This file is automatically generated by synchronize.py
# To change the list of source files, update the QT_ files and run D:\dev\git\simulationcraft\source_files\synchronize.py


 SOURCES += engine/sc_main.cpp