# This file is automatically generated by update.py
# Last updated: 2014-01-27 16:21:50.372284

# To change the list of source files, update the QT_ files and run update.py


 SOURCES += engine/sc_main.cpp