# This file is automatically generated by update.py
# Last updated: 2014-02-16 11:27:37.758525

# To change the list of source files, update the QT_ files and run update.py


 SOURCES += engine/sc_main.cpp