# This file is automatically generated by update.py
# Last updated: 2014-01-04 22:29:51.598474

# To change the list of source files, update the QT_ files and run update.py


 HEADERS += qt/simulationcraftqt.hpp
 HEADERS += qt/SC_OptionsTab.hpp
 HEADERS += qt/sc_autoupdate.h
 SOURCES += qt/main.cpp
 SOURCES += qt/sc_window.cpp
 SOURCES += qt/sc_import.cpp
 SOURCES += qt/sc_options_tab.cpp