# This file is automatically generated by synchronize.py
# To change the list of source files, update the QT_ files and run synchronize.py


 HEADERS += qt/util/sc_textedit.hpp
 HEADERS += qt/util/sc_searchbox.hpp
 HEADERS += qt/simulationcraftqt.hpp
 HEADERS += qt/SC_OptionsTab.hpp
 SOURCES += qt/util/sc_textedit.cpp
 SOURCES += qt/util/sc_searchbox.cpp
 SOURCES += qt/sc_window.cpp
 SOURCES += qt/sc_options_tab.cpp
 SOURCES += qt/sc_import.cpp
 SOURCES += qt/main.cpp