// Class based active abilities, wow build 12857
static unsigned __class_ability_data[][110] = {
  {
        0,
  },
  // Class active abilities for Warrior, 56 abilities
  {
     6673, // Battle Shout
     2457, // Battle Stance
    18499, // Berserker Rage
     2458, // Berserker Stance
    46924, // Bladestorm
     2687, // Bloodrage
    23881, // Bloodthirst
     1161, // Challenging Shout
      100, // Charge
      845, // Cleave
    86346, // Colossus Smash
      469, // Commanding Shout
    12809, // Concussion Blow
    85730, // Deadly Calm
    12292, // Death Wish
       71, // Defensive Stance
     1160, // Demoralizing Shout
    20243, // Devastate
      676, // Disarm
    55694, // Enraged Regeneration
     5308, // Execute
     1715, // Hamstring
    60970, // Heroic Fury
     6544, // Heroic Leap
       78, // Heroic Strike
    57755, // Heroic Throw
    20252, // Intercept
     3411, // Intervene
     5246, // Intimidating Shout
    12975, // Last Stand
    12294, // Mortal Strike
     7384, // Overpower
    12323, // Piercing Howl
     6552, // Pummel
    85288, // Raging Blow
     1719, // Recklessness
      772, // Rend
    20230, // Retaliation
     6572, // Revenge
    64382, // Shattering Throw
       72, // Shield Bash
     2565, // Shield Block
    23922, // Shield Slam
      871, // Shield Wall
    46968, // Shockwave
     1464, // Slam
    23920, // Spell Reflection
    88161, // Strike
     7386, // Sunder Armor
    12328, // Sweeping Strikes
      355, // Taunt
    85388, // Throwdown
     6343, // Thunder Clap
    34428, // Victory Rush
    50720, // Vigilance
     1680, // Whirlwind
        0,
  },
  // Class active abilities for Paladin, 54 abilities
  {
    31850, // Ardent Defender
    31935, // Avenger's Shield
    31884, // Avenging Wrath
    53563, // Beacon of Light
    20217, // Blessing of Kings
    19740, // Blessing of Might
    31803, // Censure
     4987, // Cleanse
    19746, // Concentration Aura
    26573, // Consecration
    32223, // Crusader Aura
    35395, // Crusader Strike
      465, // Devotion Aura
    31842, // Divine Favor
    70940, // Divine Guardian
    82326, // Divine Light
    54428, // Divine Plea
      498, // Divine Protection
      642, // Divine Shield
    53385, // Divine Storm
      879, // Exorcism
    19750, // Flash of Light
    86150, // Guardian of Ancient Kings
      853, // Hammer of Justice
    24275, // Hammer of Wrath
    53595, // Hammer of the Righteous
     1044, // Hand of Freedom
     1022, // Hand of Protection
    62124, // Hand of Reckoning
     6940, // Hand of Sacrifice
     1038, // Hand of Salvation
      635, // Holy Light
    64891, // Holy Mending
    82327, // Holy Radiance
    20473, // Holy Shock
     2812, // Holy Wrath
    84963, // Inquisition
    20271, // Judgement
      633, // Lay on Hands
    85222, // Light of Dawn
    85285, // Rebuke
    20066, // Repentance
    19891, // Resistance Aura
     7294, // Retribution Aura
    31789, // Righteous Defense
    25780, // Righteous Fury
    20165, // Seal of Insight
    20164, // Seal of Justice
    20154, // Seal of Righteousness
    31801, // Seal of Truth
    53600, // Shield of the Righteous
    85256, // Templar's Verdict
    85673, // Word of Glory
    85696, // Zealotry
        0,
  },
  // Class active abilities for Hunter, 110 abilities
  {
    19434, // Aimed Shot
     3044, // Arcane Shot
     5118, // Aspect of the Cheetah
    82661, // Aspect of the Fox
    13165, // Aspect of the Hawk
    13159, // Aspect of the Pack
    20043, // Aspect of the Wild
       75, // Auto Shot
    50433, // Bad Attitude
     1462, // Beast Lore
    19574, // Bestial Wrath
    17253, // Bite
     3674, // Black Arrow
      883, // Call Pet 1
    83242, // Call Pet 2
    83243, // Call Pet 3
    83244, // Call Pet 4
    83245, // Call Pet 5
    53434, // Call of the Wild
    51753, // Camouflage
    61685, // Charge
    53209, // Chimera Shot
    16827, // Claw
    77767, // Cobra Shot
     5116, // Concussive Shot
    19306, // Counterattack
     1742, // Cower
    24423, // Demoralizing Screech
    19263, // Deterrence
     2641, // Dismiss Pet
    20736, // Distracting Shot
    50285, // Dust Cloud
    53301, // Explosive Shot
    13813, // Explosive Trap
    34501, // Expose Weakness
    75447, // Ferocious Inspiration
    82726, // Fervor
    34889, // Fire Breath
     1543, // Flare
     1499, // Freezing Trap
    13809, // Frost Trap
    54644, // Froststorm Breath
    24604, // Furious Howl
    35290, // Gore
     2649, // Growl
    55709, // Heart of the Phoenix
     1130, // Hunter's Mark
    13797, // Immolation Trap
    53476, // Intervene
    19577, // Intimidation
    34026, // Kill Command
    53351, // Kill Shot
    58604, // Lava Breath
    53426, // Lick Your Wounds
    24844, // Lightning Breath
      136, // Mend Pet
    34477, // Misdirection
    54680, // Monstrous Bite
     2643, // Multi-Shot
    50479, // Nether Shock
    50245, // Pin
    35387, // Poison Spit
    24450, // Prowl
    26090, // Pummel
    59881, // Rake
     3045, // Rapid Fire
     2973, // Raptor Strike
    50518, // Ravage
    23989, // Readiness
      982, // Revive Pet
    53517, // Roar of Recovery
    53480, // Roar of Sacrifice
    50498, // Savage Rend
    19503, // Scatter Shot
    24640, // Scorpid Poison
    50318, // Serenity Dust
     1978, // Serpent Sting
    34490, // Silencing Shot
    49966, // Smack
    34600, // Snake Trap
    50541, // Snatch
    50519, // Sonic Blast
    61193, // Spirit Strike
    50274, // Spore Cloud
    57386, // Stampede
    56641, // Steady Shot
    56626, // Sting
    50256, // Swipe
    52825, // Swoop
     1515, // Tame Beast
    53477, // Taunt
    50271, // Tendon Rip
    34471, // The Beast Within
    63900, // Thunderstomp
     1494, // Track Beasts
    19878, // Track Demons
    19879, // Track Dragonkin
    19880, // Track Elementals
    19882, // Track Giants
    19883, // Track Humanoids
    19884, // Track Undead
    19801, // Tranquilizing Shot
    77769, // Trap Launcher
    54706, // Venom Web Spray
    35346, // Warp
     4167, // Web
    82654, // Widow Venom
     2974, // Wing Clip
    53508, // Wolverine Bite
    19386, // Wyvern Sting
  },
  // Class active abilities for Rogue, 39 abilities
  {
    13750, // Adrenaline Rush
     8676, // Ambush
       53, // Backstab
    13877, // Blade Flurry
     2094, // Blind
     1833, // Cheap Shot
    31224, // Cloak of Shadows
    26679, // Deadly Throw
    51722, // Dismantle
     1725, // Distract
    32645, // Envenom
     5277, // Evasion
     2098, // Eviscerate
     8647, // Expose Armor
    51723, // Fan of Knives
     1966, // Feint
      703, // Garrote
     1776, // Gouge
    16511, // Hemorrhage
     1766, // Kick
      408, // Kidney Shot
    51690, // Killing Spree
     1329, // Mutilate
    14185, // Preparation
    73651, // Recuperate
    73981, // Redirect
    84617, // Revealing Strike
    14251, // Riposte
     1943, // Rupture
     6770, // Sap
    36554, // Shadowstep
     5938, // Shiv
     1752, // Sinister Strike
     5171, // Slice and Dice
    76577, // Smoke Bomb
     1784, // Stealth
    57934, // Tricks of the Trade
     1856, // Vanish
    79140, // Vendetta
        0,
  },
  // Class active abilities for Priest, 52 abilities
  {
    87151, // Archangel
    32546, // Binding Heal
    14751, // Chakra
    34861, // Circle of Healing
      528, // Cure Disease
    19236, // Desperate Prayer
     2944, // Devouring Plague
      527, // Dispel Magic
    47585, // Dispersion
    64843, // Divine Hymn
      586, // Fade
     6346, // Fear Ward
     2061, // Flash Heal
     2060, // Greater Heal
    47788, // Guardian Spirit
     2050, // Heal
    14914, // Holy Fire
    15237, // Holy Nova
    88625, // Holy Word: Chastise
    64901, // Hymn of Hope
      588, // Inner Fire
    89485, // Inner Focus
    73413, // Inner Will
     1706, // Levitate
      724, // Lightwell
     8129, // Mana Burn
    32375, // Mass Dispel
     8092, // Mind Blast
      605, // Mind Control
    15407, // Mind Flay
    48045, // Mind Sear
    73510, // Mind Spike
    33206, // Pain Suppression
    47540, // Penance
    10060, // Power Infusion
    62618, // Power Word: Barrier
    21562, // Power Word: Fortitude
       17, // Power Word: Shield
      596, // Prayer of Healing
    33076, // Prayer of Mending
    64044, // Psychic Horror
      139, // Renew
     9484, // Shackle Undead
    27683, // Shadow Protection
    32379, // Shadow Word: Death
      589, // Shadow Word: Pain
    34433, // Shadowfiend
    15473, // Shadowform
    15487, // Silence
      585, // Smite
    15286, // Vampiric Embrace
    34914, // Vampiric Touch
        0,
  },
  // Class active abilities for Death Knight, 44 abilities
  {
    48707, // Anti-Magic Shell
    51052, // Anti-Magic Zone
    42650, // Army of the Dead
    48721, // Blood Boil
    48263, // Blood Presence
    45902, // Blood Strike
    45529, // Blood Tap
    49222, // Bone Shield
    45524, // Chains of Ice
    47468, // Claw
    49028, // Dancing Rune Weapon
    56222, // Dark Command
    77606, // Dark Simulacrum
    47541, // Death Coil
    49998, // Death Strike
    43265, // Death and Decay
    85948, // Festering Strike
    48266, // Frost Presence
    63560, // Ghoul Frenzy
    47481, // Gnaw
    55050, // Heart Strike
    49184, // Howling Blast
    47484, // Huddle
    49203, // Hungering Cold
    48792, // Icebound Fortitude
    45477, // Icy Touch
    47482, // Leap
    47528, // Mind Freeze
    73975, // Necrotic Strike
    49020, // Obliterate
    77575, // Outbreak
     3714, // Path of Frost
    50842, // Pestilence
    51271, // Pillar of Frost
    45462, // Plague Strike
    66217, // Rune Strike
    56815, // Rune Strike
    48982, // Rune Tap
    55090, // Scourge Strike
    47476, // Strangulate
    49206, // Summon Gargoyle
    50536, // Unholy Blight
    48265, // Unholy Presence
    55233, // Vampiric Blood
        0,
  },
  // Class active abilities for Shaman, 56 abilities
  {
    76780, // Bind Elemental
     1064, // Chain Heal
      421, // Chain Lightning
    51886, // Cleanse Spirit
     2062, // Earth Elemental Totem
      974, // Earth Shield
     8042, // Earth Shock
     2484, // Earthbind Totem
    51730, // Earthliving Weapon
    61882, // Earthquake
    16166, // Elemental Mastery
     8184, // Elemental Resistance Totem
    51533, // Feral Spirit
     2894, // Fire Elemental Totem
     1535, // Fire Nova
     8050, // Flame Shock
     8227, // Flametongue Totem
     8024, // Flametongue Weapon
     8056, // Frost Shock
     8033, // Frostbrand Weapon
     2645, // Ghost Wolf
    77472, // Greater Healing Wave
     8177, // Grounding Totem
     5394, // Healing Stream Totem
      331, // Healing Wave
    51514, // Hex
    51505, // Lava Burst
    60103, // Lava Lash
     8004, // Lesser Healing Wave
      403, // Lightning Bolt
      324, // Lightning Shield
     8190, // Magma Totem
     5675, // Mana Spring Totem
    16190, // Mana Tide Totem
    16188, // Nature's Swiftness
    73899, // Primal Strike
      370, // Purge
    61295, // Riptide
     8017, // Rockbiter Weapon
     3599, // Searing Totem
    30823, // Shamanistic Rage
    79206, // Spiritwalker's Grace
     5730, // Stoneclaw Totem
     8071, // Stoneskin Totem
    17364, // Stormstrike
     8075, // Strength of Earth Totem
    51490, // Thunderstorm
    87718, // Totem of Tranquil Mind
     8143, // Tremor Totem
    73680, // Unleash Elements
      131, // Water Breathing
    52127, // Water Shield
    57994, // Wind Shear
     8512, // Windfury Totem
     8232, // Windfury Weapon
     3738, // Wrath of Air Totem
        0,
  },
  // Class active abilities for Mage, 47 abilities
  {
    44425, // Arcane Barrage
    30451, // Arcane Blast
     1449, // Arcane Explosion
     1459, // Arcane Intellect
     5143, // Arcane Missiles
    12042, // Arcane Power
    11113, // Blast Wave
    31643, // Blazing Speed
     1953, // Blink
       10, // Blizzard
    11958, // Cold Snap
    11129, // Combustion
      120, // Cone of Cold
      759, // Conjure Mana Gem
     2139, // Counterspell
    82676, // Curtain of Frost
    61316, // Dalaran Brilliance
    44572, // Deep Freeze
    31661, // Dragon's Breath
    12051, // Evocation
      133, // Fireball
    82731, // Flame Orb
    54646, // Focus Magic
    33395, // Freeze
     7302, // Frost Armor
      122, // Frost Nova
      116, // Frostbolt
    44614, // Frostfire Bolt
    11426, // Ice Barrier
    45438, // Ice Block
    30455, // Ice Lance
    12472, // Icy Veins
       66, // Invisibility
    44457, // Living Bomb
     6117, // Mage Armor
      543, // Mage Ward
     1463, // Mana Shield
    55342, // Mirror Image
    30482, // Molten Armor
    12043, // Presence of Mind
    11366, // Pyroblast
      475, // Remove Curse
     2948, // Scorch
    31589, // Slow
    31687, // Summon Water Elemental
    80353, // Time Warp
    31707, // Waterbolt
        0,
  },
  // Class active abilities for Warlock, 76 abilities
  {
    89766, // Axe Toss
      980, // Bane of Agony
      603, // Bane of Doom
    80240, // Bane of Havoc
      710, // Banish
     6307, // Blood Pact
    50796, // Chaos Bolt
    17962, // Conflagrate
    17767, // Consume Shadows
      172, // Corruption
     6201, // Create Healthstone
      693, // Create Soulstone
    18223, // Curse of Exhaustion
     1714, // Curse of Tongues
      702, // Curse of Weakness
     1490, // Curse of the Elements
    80398, // Dark Intent
     6789, // Death Coil
      687, // Demon Armor
    77801, // Demon Soul
    47193, // Demonic Empowerment
    53646, // Demonic Pact
    88448, // Demonic Rebirth
    19505, // Devour Magic
      689, // Drain Life
     5138, // Drain Mana
     1120, // Drain Soul
     1098, // Enslave Demon
    28176, // Fel Armor
    77799, // Fel Flame
    54424, // Fel Intelligence
    89751, // Felstorm <NNF>
     3110, // Firebolt
    89792, // Flee
    71521, // Hand of Gul'dan
    48181, // Haunt
      755, // Health Funnel
     1949, // Hellfire
      348, // Immolate
    29722, // Incinerate
     7814, // Lash of Pain
    30213, // Legion Strike
     7870, // Lesser Invisibility
     1454, // Life Tap
    30151, // Pursuit
     5740, // Rain of Fire
     5676, // Searing Pain
     6358, // Seduction
    27243, // Seed of Corruption
    54049, // Shadow Bite
      686, // Shadow Bolt
     6229, // Shadow Ward
    17877, // Shadowburn
    47897, // Shadowflame
    30283, // Shadowfury
    89808, // Singe Magic
     6353, // Soul Fire
    79268, // Soul Harvest
    19028, // Soul Link
    86121, // Soul Swap
    74434, // Soulburn
    29858, // Soulshatter
    19647, // Spell Lock
    53756, // Sudden Fear
    17735, // Suffering
    18540, // Summon Doomguard
    30146, // Summon Felguard
      691, // Summon Felhunter
      688, // Summon Imp
     1122, // Summon Infernal
      712, // Summon Succubus
      697, // Summon Voidwalker
     3716, // Torment
     5697, // Unending Breath
    30108, // Unstable Affliction
     6360, // Whiplash
        0,
  },
  {
        0,
  },
  // Class active abilities for Druid, 68 abilities
  {
     1066, // Aquatic Form
    22812, // Barkskin
     5211, // Bash
     5487, // Bear Form
    50334, // Berserk
      768, // Cat Form
     5209, // Challenging Roar
     1082, // Claw
     8998, // Cower
    33786, // Cyclone
       99, // Demoralizing Roar
     5229, // Enrage
      339, // Entangling Roots
      770, // Faerie Fire
    16857, // Faerie Fire (Feral)
    22568, // Ferocious Bite
    33943, // Flight Form
    33831, // Force of Nature
    22842, // Frenzied Regeneration
     6795, // Growl
     5185, // Healing Touch
     2637, // Hibernate
    16914, // Hurricane
    29166, // Innervate
     5570, // Insect Swarm
    33745, // Lacerate
    33763, // Lifebloom
    22570, // Maim
     1126, // Mark of the Wild
     6807, // Maul
     8921, // Moonfire
    24858, // Moonkin Form
    16689, // Nature's Grasp
    17116, // Nature's Swiftness
    50464, // Nourish
     9005, // Pounce
     5215, // Prowl
    80313, // Pulverize
     1822, // Rake
     6785, // Ravage
     8936, // Regrowth
      774, // Rejuvenation
     2782, // Remove Corruption
     1079, // Rip
    52610, // Savage Roar
     5221, // Shred
    80964, // Skull Bash
    80965, // Skull Bash
    78675, // Solar Beam
     2908, // Soothe
    48505, // Starfall
     2912, // Starfire
    78674, // Starsurge
    61336, // Survival Instincts
    40120, // Swift Flight Form
    18562, // Swiftmend
      779, // Swipe
    62078, // Swipe
      467, // Thorns
    77758, // Thrash
     5217, // Tiger's Fury
      740, // Tranquility
      783, // Travel Form
    50516, // Typhoon
    48438, // Wild Growth
    77765, // Wild Mushroom
    77766, // Wild Mushroom: Detonate
     5176, // Wrath
        0,
  },
};

