// Class mastery abilities, wow build 12857
static unsigned __class_mastery_ability_data[][4] = {
  {
        0,
  },
  // Class mastery abilities for Warrior
  {
    76857, // Critical Block
    76838, // Strikes of Opportunity
    76856, // Unshackled Fury
        0,
  },
  // Class mastery abilities for Paladin
  {
    76671, // Divine Bulwark
    76672, // Hand of Light
    76669, // Illuminated Healing
        0,
  },
  // Class mastery abilities for Hunter
  {
    76657, // Master of Beasts
    76658, // One With Nature
    76659, // Wild Quiver
        0,
  },
  // Class mastery abilities for Rogue
  {
    76808, // Executioner
    76806, // Main Gauche
    76803, // Potent Poisons
        0,
  },
  // Class mastery abilities for Priest
  {
    77485, // Echo of Light
    77486, // Shadow Orbs
    77484, // Shield Discipline
        0,
  },
  // Class mastery abilities for Death Knight
  {
    77515, // Blightcaller
    77513, // Blood Shield
    77514, // Frozen Heart
        0,
  },
  // Class mastery abilities for Shaman
  {
    77226, // Deep Healing
    77222, // Elemental Overload
    77223, // Enhanced Elements
        0,
  },
  // Class mastery abilities for Mage
  {
    76595, // Flashburn
    76613, // Frostburn
    76547, // Mana Adept
        0,
  },
  // Class mastery abilities for Warlock
  {
    77220, // Fiery Apocalypse
    77219, // Master Demonologist
    77215, // Potent Afflictions
        0,
  },
  {
        0,
  },
  // Class mastery abilities for Druid
  {
    77495, // Deep Healing
    77493, // Razor Claws
    77494, // Savage Defender
    77492, // Total Eclipse
  },
};

