// Class based active abilities, wow build 12942
static unsigned __ptr_class_ability_data[][115] = {
  {
        0,
  },
  // Class active abilities for Warrior, 54 abilities
  {
     6673, // Battle Shout
     2457, // Battle Stance
    18499, // Berserker Rage
     2458, // Berserker Stance
    46924, // Bladestorm
    23881, // Bloodthirst
     1161, // Challenging Shout
      100, // Charge
      845, // Cleave
    86346, // Colossus Smash
      469, // Commanding Shout
    12809, // Concussion Blow
    12292, // Death Wish
       71, // Defensive Stance
     1160, // Demoralizing Shout
    20243, // Devastate
      676, // Disarm
    55694, // Enraged Regeneration
     5308, // Execute
     1715, // Hamstring
    60970, // Heroic Fury
     6544, // Heroic Leap
       78, // Heroic Strike
    57755, // Heroic Throw
    20252, // Intercept
     3411, // Intervene
     5246, // Intimidating Shout
    12975, // Last Stand
    12294, // Mortal Strike
     7384, // Overpower
    12323, // Piercing Howl
     6552, // Pummel
    85288, // Raging Blow
     1719, // Recklessness
      772, // Rend
    20230, // Retaliation
     6572, // Revenge
    64382, // Shattering Throw
       72, // Shield Bash
     2565, // Shield Block
    23922, // Shield Slam
      871, // Shield Wall
    46968, // Shockwave
     1464, // Slam
    23920, // Spell Reflection
    88161, // Strike
     7386, // Sunder Armor
    12328, // Sweeping Strikes
      355, // Taunt
    85388, // Throwdown
     6343, // Thunder Clap
    34428, // Victory Rush
    50720, // Vigilance
     1680, // Whirlwind
        0,
  },
  // Class active abilities for Paladin, 56 abilities
  {
    31850, // Ardent Defender
    31935, // Avenger's Shield
    31884, // Avenging Wrath
    53563, // Beacon of Light
    20217, // Blessing of Kings
    19740, // Blessing of Might
    31803, // Censure
     4987, // Cleanse
    19746, // Concentration Aura
    26573, // Consecration
    32223, // Crusader Aura
    35395, // Crusader Strike
      465, // Devotion Aura
    31842, // Divine Favor
    70940, // Divine Guardian
    82326, // Divine Light
    54428, // Divine Plea
      498, // Divine Protection
      642, // Divine Shield
    53385, // Divine Storm
      879, // Exorcism
    19750, // Flash of Light
    86150, // Guardian of Ancient Kings
      853, // Hammer of Justice
    24275, // Hammer of Wrath
    53595, // Hammer of the Righteous
     1044, // Hand of Freedom
     1022, // Hand of Protection
    62124, // Hand of Reckoning
     6940, // Hand of Sacrifice
     1038, // Hand of Salvation
      635, // Holy Light
    64891, // Holy Mending
    82327, // Holy Radiance
    25912, // Holy Shock
    25914, // Holy Shock
    20473, // Holy Shock
     2812, // Holy Wrath
    84963, // Inquisition
    20271, // Judgement
      633, // Lay on Hands
    85222, // Light of Dawn
    85285, // Rebuke
    20066, // Repentance
    19891, // Resistance Aura
     7294, // Retribution Aura
    31789, // Righteous Defense
    25780, // Righteous Fury
    20165, // Seal of Insight
    20164, // Seal of Justice
    20154, // Seal of Righteousness
    31801, // Seal of Truth
    53600, // Shield of the Righteous
    85256, // Templar's Verdict
    85673, // Word of Glory
    85696, // Zealotry
        0,
  },
  // Class active abilities for Hunter, 115 abilities
  {
    19434, // Aimed Shot
    90355, // Ancient Hysteria
    50433, // Ankle Crack
     3044, // Arcane Shot
     5118, // Aspect of the Cheetah
    82661, // Aspect of the Fox
    13165, // Aspect of the Hawk
    13159, // Aspect of the Pack
    20043, // Aspect of the Wild
       75, // Auto Shot
     1462, // Beast Lore
    19574, // Bestial Wrath
    17253, // Bite
     3674, // Black Arrow
      883, // Call Pet 1
    83242, // Call Pet 2
    83243, // Call Pet 3
    83244, // Call Pet 4
    83245, // Call Pet 5
    53434, // Call of the Wild
    51753, // Camouflage
    61685, // Charge
    53209, // Chimera Shot
    16827, // Claw
    50541, // Clench
    77767, // Cobra Shot
     5116, // Concussive Shot
    35387, // Corrosive Spit
    19306, // Counterattack
     1742, // Cower
    50256, // Demoralizing Roar
    24423, // Demoralizing Screech
    19263, // Deterrence
     2641, // Dismiss Pet
    20736, // Distracting Shot
    50285, // Dust Cloud
    53301, // Explosive Shot
    13813, // Explosive Trap
    75447, // Ferocious Inspiration
    82726, // Fervor
    34889, // Fire Breath
     1543, // Flare
     1499, // Freezing Trap
    54644, // Frost Breath
    24604, // Furious Howl
    35290, // Gore
     2649, // Growl
    55709, // Heart of the Phoenix
     1130, // Hunter's Mark
    13809, // Ice Trap
    13797, // Immolation Trap
    53476, // Intervene
    19577, // Intimidation
    34026, // Kill Command
    53351, // Kill Shot
    58604, // Lava Breath
    53426, // Lick Your Wounds
    24844, // Lightning Breath
      136, // Mend Pet
    34477, // Misdirection
    54680, // Monstrous Bite
     2643, // Multi-Shot
    50479, // Nether Shock
    50245, // Pin
    90347, // Play
    90328, // Prowl
    24450, // Prowl
    26090, // Pummel
    90364, // Qiraji Fortitude
    59881, // Rake
     3045, // Rapid Fire
     2973, // Raptor Strike
    50518, // Ravage
    23989, // Readiness
      982, // Revive Pet
    53517, // Roar of Recovery
    53480, // Roar of Sacrifice
    19503, // Scatter Shot
    50318, // Serenity Dust
     1978, // Serpent Sting
    34490, // Silencing Shot
    49966, // Smack
    34600, // Snake Trap
    91644, // Snatch
    50519, // Sonic Blast
    90361, // Spirit Mend
    50274, // Spore Cloud
    57386, // Stampede
    56641, // Steady Shot
    56626, // Sting
    52825, // Swoop
    90314, // Tailspin
     1515, // Tame Beast
    53477, // Taunt
    50498, // Tear Armor
    50271, // Tendon Rip
    90309, // Terrifying Roar
    34471, // The Beast Within
    63900, // Thunderstomp
    35346, // Time Warp
     1494, // Track Beasts
    19878, // Track Demons
    19879, // Track Dragonkin
    19880, // Track Elementals
    19882, // Track Giants
    19883, // Track Humanoids
    19884, // Track Undead
    19801, // Tranquilizing Shot
    77769, // Trap Launcher
    54706, // Venom Web Spray
     4167, // Web
    82654, // Widow Venom
     2974, // Wing Clip
    53508, // Wolverine Bite
    19386, // Wyvern Sting
  },
  // Class active abilities for Rogue, 39 abilities
  {
    13750, // Adrenaline Rush
     8676, // Ambush
       53, // Backstab
    13877, // Blade Flurry
     2094, // Blind
     1833, // Cheap Shot
    31224, // Cloak of Shadows
    26679, // Deadly Throw
    51722, // Dismantle
     1725, // Distract
    32645, // Envenom
     5277, // Evasion
     2098, // Eviscerate
     8647, // Expose Armor
    51723, // Fan of Knives
     1966, // Feint
      703, // Garrote
     1776, // Gouge
    16511, // Hemorrhage
     1766, // Kick
      408, // Kidney Shot
    51690, // Killing Spree
     1329, // Mutilate
    14185, // Preparation
    73651, // Recuperate
    73981, // Redirect
    84617, // Revealing Strike
    14251, // Riposte
     1943, // Rupture
     6770, // Sap
    36554, // Shadowstep
     5938, // Shiv
     1752, // Sinister Strike
     5171, // Slice and Dice
    76577, // Smoke Bomb
     1784, // Stealth
    57934, // Tricks of the Trade
     1856, // Vanish
    79140, // Vendetta
        0,
  },
  // Class active abilities for Priest, 53 abilities
  {
    87151, // Archangel
    32546, // Binding Heal
    14751, // Chakra
    34861, // Circle of Healing
      528, // Cure Disease
    19236, // Desperate Prayer
     2944, // Devouring Plague
      527, // Dispel Magic
    47585, // Dispersion
    64843, // Divine Hymn
      586, // Fade
     6346, // Fear Ward
     2061, // Flash Heal
     2060, // Greater Heal
    47788, // Guardian Spirit
     2050, // Heal
    14914, // Holy Fire
    15237, // Holy Nova
    88625, // Holy Word: Chastise
    64901, // Hymn of Hope
      588, // Inner Fire
    89485, // Inner Focus
    73413, // Inner Will
     1706, // Levitate
      724, // Lightwell
     8129, // Mana Burn
    32375, // Mass Dispel
     8092, // Mind Blast
      605, // Mind Control
    15407, // Mind Flay
    48045, // Mind Sear
    73510, // Mind Spike
    33206, // Pain Suppression
    47540, // Penance
    10060, // Power Infusion
    62618, // Power Word: Barrier
    21562, // Power Word: Fortitude
       17, // Power Word: Shield
      596, // Prayer of Healing
    33076, // Prayer of Mending
    64044, // Psychic Horror
     8122, // Psychic Scream
      139, // Renew
     9484, // Shackle Undead
    27683, // Shadow Protection
    32379, // Shadow Word: Death
      589, // Shadow Word: Pain
    34433, // Shadowfiend
    15473, // Shadowform
    15487, // Silence
      585, // Smite
    15286, // Vampiric Embrace
    34914, // Vampiric Touch
        0,
  },
  // Class active abilities for Death Knight, 52 abilities
  {
    48707, // Anti-Magic Shell
    51052, // Anti-Magic Zone
    42650, // Army of the Dead
    48721, // Blood Boil
    48263, // Blood Presence
    45902, // Blood Strike
    45529, // Blood Tap
    49222, // Bone Shield
    45524, // Chains of Ice
    47468, // Claw
    91776, // Claw
    49028, // Dancing Rune Weapon
    56222, // Dark Command
    77606, // Dark Simulacrum
    63560, // Dark Transformation
    47541, // Death Coil
    49998, // Death Strike
    43265, // Death and Decay
    85948, // Festering Strike
    48266, // Frost Presence
    47481, // Gnaw
    91800, // Gnaw
    55050, // Heart Strike
    49184, // Howling Blast
    91838, // Huddle
    47484, // Huddle
    49203, // Hungering Cold
    48792, // Icebound Fortitude
    45477, // Icy Touch
    47482, // Leap
    91809, // Leap
    47528, // Mind Freeze
    91797, // Monstrous Blow
    73975, // Necrotic Strike
    49020, // Obliterate
    77575, // Outbreak
     3714, // Path of Frost
    50842, // Pestilence
    51271, // Pillar of Frost
    45462, // Plague Strike
    91837, // Putrid Bulwark
    66217, // Rune Strike
    56815, // Rune Strike
    48982, // Rune Tap
    55090, // Scourge Strike
    91802, // Shambling Rush
    47476, // Strangulate
    49206, // Summon Gargoyle
    91778, // Sweeping Claws
    50536, // Unholy Blight
    48265, // Unholy Presence
    55233, // Vampiric Blood
        0,
  },
  // Class active abilities for Shaman, 56 abilities
  {
    76780, // Bind Elemental
     1064, // Chain Heal
      421, // Chain Lightning
    51886, // Cleanse Spirit
     2062, // Earth Elemental Totem
      974, // Earth Shield
     8042, // Earth Shock
     2484, // Earthbind Totem
    51730, // Earthliving Weapon
    61882, // Earthquake
    16166, // Elemental Mastery
     8184, // Elemental Resistance Totem
    51533, // Feral Spirit
     2894, // Fire Elemental Totem
     1535, // Fire Nova
     8050, // Flame Shock
     8227, // Flametongue Totem
     8024, // Flametongue Weapon
     8056, // Frost Shock
     8033, // Frostbrand Weapon
     2645, // Ghost Wolf
    77472, // Greater Healing Wave
     8177, // Grounding Totem
     5394, // Healing Stream Totem
     8004, // Healing Surge
      331, // Healing Wave
    51514, // Hex
    51505, // Lava Burst
    60103, // Lava Lash
      403, // Lightning Bolt
      324, // Lightning Shield
     8190, // Magma Totem
     5675, // Mana Spring Totem
    16190, // Mana Tide Totem
    16188, // Nature's Swiftness
    73899, // Primal Strike
      370, // Purge
    61295, // Riptide
     8017, // Rockbiter Weapon
     3599, // Searing Totem
    30823, // Shamanistic Rage
    79206, // Spiritwalker's Grace
     5730, // Stoneclaw Totem
     8071, // Stoneskin Totem
    17364, // Stormstrike
     8075, // Strength of Earth Totem
    51490, // Thunderstorm
    87718, // Totem of Tranquil Mind
     8143, // Tremor Totem
    73680, // Unleash Elements
      131, // Water Breathing
    52127, // Water Shield
    57994, // Wind Shear
     8512, // Windfury Totem
     8232, // Windfury Weapon
     3738, // Wrath of Air Totem
        0,
  },
  // Class active abilities for Mage, 52 abilities
  {
    44425, // Arcane Barrage
    30451, // Arcane Blast
     1459, // Arcane Brilliance
     1449, // Arcane Explosion
     5143, // Arcane Missiles
    12042, // Arcane Power
    11113, // Blast Wave
    31643, // Blazing Speed
     1953, // Blink
       10, // Blizzard
    12536, // Clearcasting
    11958, // Cold Snap
    11129, // Combustion
      120, // Cone of Cold
      759, // Conjure Mana Gem
     2139, // Counterspell
    22959, // Critical Mass
    82676, // Curtain of Frost
    61316, // Dalaran Brilliance
    44572, // Deep Freeze
    31661, // Dragon's Breath
    12051, // Evocation
     2136, // Fire Blast
      133, // Fireball
    82731, // Flame Orb
     2120, // Flamestrike
    54646, // Focus Magic
    33395, // Freeze
     7302, // Frost Armor
      122, // Frost Nova
      116, // Frostbolt
    44614, // Frostfire Bolt
    11426, // Ice Barrier
    45438, // Ice Block
    30455, // Ice Lance
    12472, // Icy Veins
    12355, // Impact
       66, // Invisibility
    44457, // Living Bomb
     6117, // Mage Armor
      543, // Mage Ward
     1463, // Mana Shield
    55342, // Mirror Image
    30482, // Molten Armor
    12043, // Presence of Mind
    11366, // Pyroblast
      475, // Remove Curse
     2948, // Scorch
    31589, // Slow
    31687, // Summon Water Elemental
    80353, // Time Warp
    31707, // Waterbolt
        0,
  },
  // Class active abilities for Warlock, 80 abilities
  {
    89766, // Axe Toss
      980, // Bane of Agony
      603, // Bane of Doom
    80240, // Bane of Havoc
      710, // Banish
     6307, // Blood Pact
    50796, // Chaos Bolt
    17962, // Conflagrate
    17767, // Consume Shadows
      172, // Corruption
     6201, // Create Healthstone
      693, // Create Soulstone
    18223, // Curse of Exhaustion
     1714, // Curse of Tongues
      702, // Curse of Weakness
     1490, // Curse of the Elements
    80398, // Dark Intent
     6789, // Death Coil
      687, // Demon Armor
    54785, // Demon Leap
    77801, // Demon Soul
    47193, // Demonic Empowerment
    88448, // Demonic Rebirth
    19505, // Devour Magic
      689, // Drain Life
     5138, // Drain Mana
     1120, // Drain Soul
     1098, // Enslave Demon
     5782, // Fear
    28176, // Fel Armor
    77799, // Fel Flame
    54424, // Fel Intelligence
    89751, // Felstorm <NNF>
     3110, // Firebolt
    89792, // Flee
    71521, // Hand of Gul'dan
    48181, // Haunt
      755, // Health Funnel
     1949, // Hellfire
      348, // Immolate
    50589, // Immolation Aura
    29722, // Incinerate
     7814, // Lash of Pain
    30213, // Legion Strike
     7870, // Lesser Invisibility
     1454, // Life Tap
    47241, // Metamorphosis
    91711, // Nether Ward
    30151, // Pursuit
     5740, // Rain of Fire
     5676, // Searing Pain
     6358, // Seduction
    27243, // Seed of Corruption
    54049, // Shadow Bite
      686, // Shadow Bolt
     6229, // Shadow Ward
    17877, // Shadowburn
    47897, // Shadowflame
    30283, // Shadowfury
    89808, // Singe Magic
     6353, // Soul Fire
    79268, // Soul Harvest
    19028, // Soul Link
    86121, // Soul Swap
    74434, // Soulburn
    29858, // Soulshatter
    19647, // Spell Lock
    53756, // Sudden Fear
    17735, // Suffering
    18540, // Summon Doomguard
    30146, // Summon Felguard
      691, // Summon Felhunter
      688, // Summon Imp
     1122, // Summon Infernal
      712, // Summon Succubus
      697, // Summon Voidwalker
     3716, // Torment
     5697, // Unending Breath
    30108, // Unstable Affliction
     6360, // Whiplash
        0,
  },
  {
        0,
  },
  // Class active abilities for Druid, 71 abilities
  {
     1066, // Aquatic Form
    22812, // Barkskin
     5211, // Bash
     5487, // Bear Form
    50334, // Berserk
      768, // Cat Form
     5209, // Challenging Roar
     1082, // Claw
     8998, // Cower
    33786, // Cyclone
       99, // Demoralizing Roar
     5229, // Enrage
      339, // Entangling Roots
      770, // Faerie Fire
    16857, // Faerie Fire (Feral)
    49376, // Feral Charge
    16979, // Feral Charge
    22568, // Ferocious Bite
    33943, // Flight Form
    33831, // Force of Nature
    22842, // Frenzied Regeneration
     6795, // Growl
     5185, // Healing Touch
     2637, // Hibernate
    16914, // Hurricane
    29166, // Innervate
     5570, // Insect Swarm
    33745, // Lacerate
    33763, // Lifebloom
    22570, // Maim
     1126, // Mark of the Wild
     6807, // Maul
     8921, // Moonfire
    24858, // Moonkin Form
    16689, // Nature's Grasp
    17116, // Nature's Swiftness
    50464, // Nourish
     9005, // Pounce
     5215, // Prowl
    80313, // Pulverize
     1822, // Rake
     6785, // Ravage
     8936, // Regrowth
      774, // Rejuvenation
     2782, // Remove Corruption
     1079, // Rip
    52610, // Savage Roar
     5221, // Shred
    80965, // Skull Bash
    80964, // Skull Bash
    78675, // Solar Beam
     2908, // Soothe
    48505, // Starfall
     2912, // Starfire
    78674, // Starsurge
    61336, // Survival Instincts
    40120, // Swift Flight Form
    18562, // Swiftmend
    62078, // Swipe
      779, // Swipe
      467, // Thorns
    77758, // Thrash
     5217, // Tiger's Fury
      740, // Tranquility
      783, // Travel Form
    33891, // Tree of Life
    50516, // Typhoon
    48438, // Wild Growth
    77765, // Wild Mushroom
    77766, // Wild Mushroom: Detonate
     5176, // Wrath
        0,
  },
};

// Talent tree specialization abilities, wow build 12942
static unsigned __ptr_tree_specialization_data[][3][5] = {
  {
    {
          0,
    },
    {
          0,
    },
    {
          0,
    },
  },
  // Talent Tree specialization abilities for Warrior
  {
    // Specialization abilities for Arms tree
    {
      12296, // Anger Management
      12294, // Mortal Strike
      12712, // Two-Handed Weapon Specialization
          0,
    },
    // Specialization abilities for Fury tree
    {
      23881, // Bloodthirst
      23588, // Dual Wield Specialization
      29592, // Precision
          0,
    },
    // Specialization abilities for Protection tree
    {
      29144, // Sentinel
      23922, // Shield Slam
      84839, // Vengeance
          0,
    },
  },
  // Talent Tree specialization abilities for Paladin
  {
    // Specialization abilities for Holy tree
    {
      20473, // Holy Shock
      85101, // Meditation
      85102, // Walk in the Light
          0,
    },
    // Specialization abilities for Protection tree
    {
      31935, // Avenger's Shield
      31878, // Judgements of the Wise
      53592, // Touched by the Light
      84839, // Vengeance
          0,
    },
    // Specialization abilities for Retribution tree
    {
      89901, // Judgements of the Bold
      53503, // Sheath of Light
      85256, // Templar's Verdict
      20113, // Two-Handed Weapon Specialization
          0,
    },
  },
  // Talent Tree specialization abilities for Hunter
  {
    // Specialization abilities for Beast Mastery tree
    {
      87325, // Animal Handler
      19577, // Intimidation
          0,
    },
    // Specialization abilities for Marksmanship tree
    {
      19434, // Aimed Shot
      87326, // Artisan Quiver
          0,
    },
    // Specialization abilities for Survival tree
    {
      53301, // Explosive Shot
      84729, // Into the Wilderness
          0,
    },
  },
  // Talent Tree specialization abilities for Rogue
  {
    // Specialization abilities for Assassination tree
    {
      84601, // Assassin's Resolve
      14117, // Improved Poisons
       1329, // Mutilate
          0,
    },
    // Specialization abilities for Combat tree
    {
      13877, // Blade Flurry
      13852, // Dual Wield Specialization
      61329, // Vitality
          0,
    },
    // Specialization abilities for Subtlety tree
    {
      31223, // Master of Subtlety
      36554, // Shadowstep
      31220, // Sinister Calling
          0,
    },
  },
  // Talent Tree specialization abilities for Priest
  {
    // Specialization abilities for Discipline tree
    {
      84732, // Enlightenment
      85101, // Meditation
      47540, // Penance
          0,
    },
    // Specialization abilities for Holy tree
    {
      88625, // Holy Word: Chastise
      85101, // Meditation
      87336, // Spiritual Healing
          0,
    },
    // Specialization abilities for Shadow tree
    {
      15407, // Mind Flay
      87327, // Shadow Power
          0,
    },
  },
  // Talent Tree specialization abilities for Death Knight
  {
    // Specialization abilities for Blood tree
    {
      50034, // Blood Rites
      55050, // Heart Strike
      84839, // Vengeance
      50029, // Veteran of the Third War
          0,
    },
    // Specialization abilities for Frost tree
    {
      54637, // Blood of the North
      49143, // Frost Strike
      50887, // Icy Talons
          0,
    },
    // Specialization abilities for Unholy tree
    {
      52143, // Master of Ghouls
      56835, // Reaping
      55090, // Scourge Strike
      91107, // Unholy Might
          0,
    },
  },
  // Talent Tree specialization abilities for Shaman
  {
    // Specialization abilities for Elemental tree
    {
      60188, // Elemental Fury
      62099, // Shamanism
      51490, // Thunderstorm
          0,
    },
    // Specialization abilities for Enhancement tree
    {
      86629, // Dual Wield
      60103, // Lava Lash
      30814, // Mental Quickness
          0,
    },
    // Specialization abilities for Restoration tree
    {
        974, // Earth Shield
      85101, // Meditation
      16213, // Purification
          0,
    },
  },
  // Talent Tree specialization abilities for Mage
  {
    // Specialization abilities for Arcane tree
    {
      44425, // Arcane Barrage
      84671, // Arcane Specialization
          0,
    },
    // Specialization abilities for Fire tree
    {
      84668, // Fire Specialization
      11366, // Pyroblast
          0,
    },
    // Specialization abilities for Frost tree
    {
      84669, // Frost Specialization
      31687, // Summon Water Elemental
          0,
    },
  },
  // Talent Tree specialization abilities for Warlock
  {
    // Specialization abilities for Affliction tree
    {
      87339, // Shadow Mastery
      30108, // Unstable Affliction
          0,
    },
    // Specialization abilities for Demonology tree
    {
      84740, // Demonic Knowledge
      30146, // Summon Felguard
          0,
    },
    // Specialization abilities for Destruction tree
    {
      84739, // Cataclysm
      17962, // Conflagrate
          0,
    },
  },
  {
    {
          0,
    },
    {
          0,
    },
    {
          0,
    },
  },
  // Talent Tree specialization abilities for Druid
  {
    // Specialization abilities for Balance tree
    {
      16913, // Moonfury
      78674, // Starsurge
          0,
    },
    // Specialization abilities for Feral Combat tree
    {
      84735, // Aggression
      87335, // Feral Instinct
      33917, // Mangle
      87793, // Shapeshifter
      84840, // Vengeance
    },
    // Specialization abilities for Restoration tree
    {
      87305, // Gift of Nature
      85101, // Meditation
      18562, // Swiftmend
          0,
    },
  },
};

// Class mastery abilities, wow build 12942
static unsigned __ptr_class_mastery_ability_data[][4] = {
  {
        0,
  },
  // Class mastery abilities for Warrior
  {
    76857, // Critical Block
    76838, // Strikes of Opportunity
    76856, // Unshackled Fury
        0,
  },
  // Class mastery abilities for Paladin
  {
    76671, // Divine Bulwark
    76672, // Hand of Light
    76669, // Illuminated Healing
        0,
  },
  // Class mastery abilities for Hunter
  {
    76658, // Essence of the Viper
    76657, // Master of Beasts
    76659, // Wild Quiver
        0,
  },
  // Class mastery abilities for Rogue
  {
    76808, // Executioner
    76806, // Main Gauche
    76803, // Potent Poisons
        0,
  },
  // Class mastery abilities for Priest
  {
    77485, // Echo of Light
    77486, // Shadow Orbs
    77484, // Shield Discipline
        0,
  },
  // Class mastery abilities for Death Knight
  {
    77515, // Blightcaller
    77513, // Blood Shield
    77514, // Frozen Heart
        0,
  },
  // Class mastery abilities for Shaman
  {
    77226, // Deep Healing
    77222, // Elemental Overload
    77223, // Enhanced Elements
        0,
  },
  // Class mastery abilities for Mage
  {
    76595, // Flashburn
    76613, // Frostburn
    76547, // Mana Adept
        0,
  },
  // Class mastery abilities for Warlock
  {
    77220, // Fiery Apocalypse
    77219, // Master Demonologist
    77215, // Potent Afflictions
        0,
  },
  {
        0,
  },
  // Class mastery abilities for Druid
  {
    77495, // Deep Healing
    77493, // Razor Claws
    77494, // Savage Defender
    77492, // Total Eclipse
  },
};

// Racial abilities, wow build 12942
static unsigned __ptr_race_ability_data[][12][6] = {
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  // Racial abilities for Human
  {
    // Generic racial abilities
    {
      59752, // Every Man for Himself
      20864, // Mace Specialization
      20597, // Sword Specialization
      20598, // The Human Spirit
          0,
    },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  // Racial abilities for Orc
  {
    // Generic racial abilities
    {
      20574, // Axe Specialization
      20573, // Hardiness
          0,
    },
    // Racial abilities for Warrior class
    {
      20572, // Blood Fury
      21563, // Command
          0,
    },
    // Racial abilities for Paladin class
    {
      21563, // Command
          0,
    },
    // Racial abilities for Hunter class
    {
      20572, // Blood Fury
      20576, // Command
          0,
    },
    // Racial abilities for Rogue class
    {
      20572, // Blood Fury
      21563, // Command
          0,
    },
    // Racial abilities for Priest class
    {
      21563, // Command
          0,
    },
    // Racial abilities for Death Knight class
    {
      20572, // Blood Fury
      54562, // Command
          0,
    },
    // Racial abilities for Shaman class
    {
      33697, // Blood Fury
      65222, // Command
          0,
    },
    // Racial abilities for Mage class
    {
      33702, // Blood Fury
      21563, // Command
          0,
    },
    // Racial abilities for Warlock class
    {
      33702, // Blood Fury
      20575, // Command
          0,
    },
    {     0, },
    // Racial abilities for Druid class
    {
      21563, // Command
          0,
    },
  },
  // Racial abilities for Dwarf
  {
    // Generic racial abilities
    {
      20596, // Frost Resistance
      20595, // Gun Specialization
      59224, // Mace Specialization
      20594, // Stoneform
          0,
    },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  // Racial abilities for Night Elf
  {
    // Generic racial abilities
    {
      20583, // Nature Resistance
      20582, // Quickness
      58984, // Shadowmeld
          0,
    },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  // Racial abilities for Undead
  {
    // Generic racial abilities
    {
      20577, // Cannibalize
      20579, // Shadow Resistance
       5227, // Underwater Breathing
       7744, // Will of the Forsaken
          0,
    },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  // Racial abilities for Tauren
  {
    // Generic racial abilities
    {
      20550, // Endurance
      20551, // Nature Resistance
      20549, // War Stomp
          0,
    },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  // Racial abilities for Gnome
  {
    // Generic racial abilities
    {
      20592, // Arcane Resistance
      20589, // Escape Artist
      20591, // Expansive Mind
          0,
    },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  // Racial abilities for Troll
  {
    // Generic racial abilities
    {
      20557, // Beast Slaying
      26297, // Berserking
      26290, // Bow Specialization
      58943, // Da Voodoo Shuffle
      20555, // Regeneration
      20558, // Throwing Specialization
    },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  // Racial abilities for Goblin
  {
    // Generic racial abilities
    {
      69041, // Rocket Barrage
      69070, // Rocket Jump
      69042, // Time is Money
          0,
    },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  // Racial abilities for Blood Elf
  {
    // Generic racial abilities
    {
        822, // Magic Resistance
          0,
    },
    // Racial abilities for Warrior class
    {
      69179, // Arcane Torrent
          0,
    },
    // Racial abilities for Paladin class
    {
      28730, // Arcane Torrent
          0,
    },
    // Racial abilities for Hunter class
    {
      28730, // Arcane Torrent
          0,
    },
    // Racial abilities for Rogue class
    {
      25046, // Arcane Torrent
          0,
    },
    // Racial abilities for Priest class
    {
      28730, // Arcane Torrent
          0,
    },
    // Racial abilities for Death Knight class
    {
      50613, // Arcane Torrent
          0,
    },
    {     0, },
    // Racial abilities for Mage class
    {
      28730, // Arcane Torrent
          0,
    },
    // Racial abilities for Warlock class
    {
      28730, // Arcane Torrent
          0,
    },
    {     0, },
    {     0, },
  },
  // Racial abilities for Draenei
  {
    {     0, },
    // Racial abilities for Warrior class
    {
      28880, // Gift of the Naaru
       6562, // Heroic Presence
      59221, // Shadow Resistance
          0,
    },
    // Racial abilities for Paladin class
    {
      59542, // Gift of the Naaru
       6562, // Heroic Presence
      59535, // Shadow Resistance
          0,
    },
    // Racial abilities for Hunter class
    {
      59543, // Gift of the Naaru
       6562, // Heroic Presence
      59536, // Shadow Resistance
          0,
    },
    {     0, },
    // Racial abilities for Priest class
    {
      59544, // Gift of the Naaru
      28878, // Heroic Presence
      59538, // Shadow Resistance
          0,
    },
    // Racial abilities for Death Knight class
    {
      59545, // Gift of the Naaru
       6562, // Heroic Presence
      59539, // Shadow Resistance
          0,
    },
    // Racial abilities for Shaman class
    {
      59547, // Gift of the Naaru
      28878, // Heroic Presence
      59540, // Shadow Resistance
          0,
    },
    // Racial abilities for Mage class
    {
      59548, // Gift of the Naaru
      28878, // Heroic Presence
      59541, // Shadow Resistance
          0,
    },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  // Racial abilities for Worgen
  {
    // Generic racial abilities
    {
      68976, // Aberration
      68975, // Viciousness
          0,
    },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
  {
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
    {     0, },
  },
};

