// Talent tree specialization abilities, wow build 12857
static unsigned __ptr_tree_specialization_data[][3][5] = {
  {
    {
          0,
    },
    {
          0,
    },
    {
          0,
    },
  },
  // Talent Tree specialization abilities for Warrior
  {
    // Specialization abilities for Arms tree
    {
      12296, // Anger Management
      12294, // Mortal Strike
      12712, // Two-Handed Weapon Specialization
          0,
    },
    // Specialization abilities for Fury tree
    {
      23881, // Bloodthirst
      23588, // Dual Wield Specialization
      29592, // Precision
          0,
    },
    // Specialization abilities for Protection tree
    {
      29144, // Sentinel
      23922, // Shield Slam
      84839, // Vengeance
          0,
    },
  },
  // Talent Tree specialization abilities for Paladin
  {
    // Specialization abilities for Holy tree
    {
      20473, // Holy Shock
      85101, // Meditation
      85102, // Walk in the Light
          0,
    },
    // Specialization abilities for Protection tree
    {
      31935, // Avenger's Shield
      31878, // Judgements of the Wise
      53592, // Touched by the Light
      84839, // Vengeance
          0,
    },
    // Specialization abilities for Retribution tree
    {
      31878, // Judgements of the Wise
      53503, // Sheath of Light
      85256, // Templar's Verdict
      20113, // Two-Handed Weapon Specialization
          0,
    },
  },
  // Talent Tree specialization abilities for Hunter
  {
    // Specialization abilities for Beast Mastery tree
    {
      87325, // Animal Handler
      19577, // Intimidation
          0,
    },
    // Specialization abilities for Marksmanship tree
    {
      19434, // Aimed Shot
      87326, // Artisan Quiver
          0,
    },
    // Specialization abilities for Survival tree
    {
      53301, // Explosive Shot
      84729, // Into the Wilderness
          0,
    },
  },
  // Talent Tree specialization abilities for Rogue
  {
    // Specialization abilities for Assassination tree
    {
      84601, // Assassin's Resolve
      14117, // Improved Poisons
       1329, // Mutilate
          0,
    },
    // Specialization abilities for Combat tree
    {
      13877, // Blade Flurry
      13852, // Dual Wield Specialization
      61329, // Vitality
          0,
    },
    // Specialization abilities for Subtlety tree
    {
      31223, // Master of Subtlety
      36554, // Shadowstep
      31220, // Sinister Calling
          0,
    },
  },
  // Talent Tree specialization abilities for Priest
  {
    // Specialization abilities for Discipline tree
    {
      84732, // Enlightenment
      85101, // Meditation
      47540, // Penance
          0,
    },
    // Specialization abilities for Holy tree
    {
      88625, // Holy Word: Chastise
      85101, // Meditation
      87336, // Spiritual Healing
          0,
    },
    // Specialization abilities for Shadow tree
    {
      15407, // Mind Flay
      87327, // Shadow Power
          0,
    },
  },
  // Talent Tree specialization abilities for Death Knight
  {
    // Specialization abilities for Blood tree
    {
      50034, // Death Rune Mastery
      55050, // Heart Strike
      84839, // Vengeance
      50029, // Veteran of the Third War
          0,
    },
    // Specialization abilities for Frost tree
    {
      54637, // Blood of the North
      49143, // Frost Strike
      50887, // Icy Talons
          0,
    },
    // Specialization abilities for Unholy tree
    {
      49638, // Impurity
      52143, // Master of Ghouls
      56835, // Reaping
      55090, // Scourge Strike
          0,
    },
  },
  // Talent Tree specialization abilities for Shaman
  {
    // Specialization abilities for Elemental tree
    {
      60188, // Elemental Fury
      29065, // Eye of the Storm
      62099, // Shamanism
      51490, // Thunderstorm
          0,
    },
    // Specialization abilities for Enhancement tree
    {
      86629, // Dual Wield
      30819, // Dual Wield Specialization
      60103, // Lava Lash
      30814, // Mental Quickness
          0,
    },
    // Specialization abilities for Restoration tree
    {
        974, // Earth Shield
      16232, // Healing Focus
      85101, // Meditation
      16213, // Purification
          0,
    },
  },
  // Talent Tree specialization abilities for Mage
  {
    // Specialization abilities for Arcane tree
    {
      44425, // Arcane Barrage
      84671, // Arcane Specialization
          0,
    },
    // Specialization abilities for Fire tree
    {
      84668, // Fire Specialization
      11366, // Pyroblast
          0,
    },
    // Specialization abilities for Frost tree
    {
      84669, // Frost Specialization
      31687, // Summon Water Elemental
          0,
    },
  },
  // Talent Tree specialization abilities for Warlock
  {
    // Specialization abilities for Affliction tree
    {
      87339, // Shadow Mastery
      30108, // Unstable Affliction
          0,
    },
    // Specialization abilities for Demonology tree
    {
      84740, // Master Demonologist
      30146, // Summon Felguard
          0,
    },
    // Specialization abilities for Destruction tree
    {
      84739, // Cataclysm
      17962, // Conflagrate
          0,
    },
  },
  {
    {
          0,
    },
    {
          0,
    },
    {
          0,
    },
  },
  // Talent Tree specialization abilities for Druid
  {
    // Specialization abilities for Balance tree
    {
      16913, // Moonfury
      78674, // Starsurge
          0,
    },
    // Specialization abilities for Feral Combat tree
    {
      84735, // Aggression
      87335, // Feral Instinct
      33917, // Mangle
      87793, // Shapeshifter
      84840, // Vengeance
    },
    // Specialization abilities for Restoration tree
    {
      87305, // Gift of Nature
      85101, // Meditation
      18562, // Swiftmend
          0,
    },
  },
};

