#!/usr/bin/env python

import sys

__max_tiers = 7
__talents_per_tier = 3
__class_map = {
    'Death_Knight': [
        (0, -1),        # 56: All
        (1, -1),        # 57: All
        (2, -1),        # 58: All
                        # 60: None
                        # 75: None
        (5, -1),        # 90: All
        (6, -1),        # 100: All
    ],
    'Druid': [
        (0, -1),        # 15: All
                        # 30: None
        (2, -1),        # 45: All
                        # 60: None
        (4, -1),        # 75: All
        (5, -1),        # 90: All
        (6, -1),        # 100: All
    ],
    'Hunter': [
        (0, -1),        # 15: All
        (1, -1),        # 30: All
                        # 45: None
        (3, -1),        # 60: All
                        # 75: None
        (5, -1),        # 90: All
        (6, -1),        # 100: All
    ],
    'Mage': [
        (0, -1),        # 15: All
                        # 30: None
        (2, -1),        # 45: All
        (3, -1),        # 60: All
                        # 75: None
        (5, -1),        # 90: All
        (6, -1),        # 100: All
    ],
    'Monk': [
        (0, -1),        # 15: All
                        # 30: None
        (2, -1),        # 45: All
        (3, 1),         # 60: Just Good Karma
                        # 75: None
        (5, -1),        # 90: All
        (6, -1),        # 100: All
    ],
    'Paladin': [
        (0, -1),        # 15: All
        (1, -1),        # 30: All
                        # 45: None
        (3, -1),        # 60: All
                        # 75: None
                        # 90: None
        (6, -1),        # 100: All
    ],
    'Priest': [
        (0, -1),        # 15: All
                        # 30: None
                        # 45: None
        (3, -1),        # 60: All
        (4, -1),        # 75: All
        (5, -1),        # 90: All
        (6, -1),        # 100: All
    ],
    'Rogue': [
        (0, -1),        # 15: All
        (1, -1),        # 30: All
        (2, -1),        # 45: All
                        # 60: None
                        # 75: None
        (5, -1),        # 90: All
        (6, -1),        # 100: All
    ],
    'Shaman': [
        (0, -1),        # 15: All
                        # 30: None
                        # 45: None
        (3, -1),        # 60: All
        (4, -1),        # 75: All
        (5, -1),        # 90: All
        (6, -1),        # 100: All
    ],
    'Warlock': [
        (0, -1),        # 15: All
        (1, -1),        # 30: All
                        # 45: None
        (3, -1),        # 60: All
                        # 75: None
        (5, -1),        # 90: All
        (6, -1),        # 100: All
    ],
    'Warrior': [
        (0, -1),        # 15: All
        (1, -1),        # 30: All
        (2, -1),        # 45: All
                        # 60: None
        (4, -1),        # 75: All
        (5, -1),        # 90: All
        (6, -1),        # 90: All
    ]
}

if len(sys.argv) < 2:
    sys.exit(1)

_class = None
for class_name in __class_map.keys():
    if class_name in sys.argv[1]:
        _class = class_name
        break

if not _class:
    sys.exit(1)

# Check untalented
combinations = [ '0' * __max_tiers ]

for talents in __class_map[_class]:
    talent_arr = [ '0' ] * __max_tiers
    if talents[1] == -1:
        for talent in xrange(0, __talents_per_tier):
            talent_arr[talents[0]] = str(talent + 1)
            talent_str = ''.join(talent_arr)

            if talent_str not in combinations:
                combinations.append(talent_str)
    else:
        talent_arr[talents[0]] = str(talents[1])
        combinations.append(''.join(talent_arr))

print ' '.join(combinations)

sys.exit(0)

