#define MAX_SPECS_PER_CLASS (4)
#define MAX_SPEC_CLASS  (13)

enum specialization_t {
  SPEC_NONE            = 0,
  WARRIOR_ARMS         = 71,
  WARRIOR_FURY         = 72,
  WARRIOR_PROTECTION   = 73,
  PALADIN_HOLY         = 65,
  PALADIN_PROTECTION   = 66,
  PALADIN_RETRIBUTION  = 70,
  HUNTER_BEAST_MASTERY = 253,
  HUNTER_MARKSMANSHIP  = 254,
  HUNTER_SURVIVAL      = 255,
  ROGUE_ASSASSINATION  = 259,
  ROGUE_COMBAT         = 260,
  ROGUE_SUBTLETY       = 261,
  PRIEST_DISCIPLINE    = 256,
  PRIEST_HOLY          = 257,
  PRIEST_SHADOW        = 258,
  DEATH_KNIGHT_BLOOD   = 250,
  DEATH_KNIGHT_FROST   = 251,
  DEATH_KNIGHT_UNHOLY  = 252,
  SHAMAN_ELEMENTAL     = 262,
  SHAMAN_ENHANCEMENT   = 263,
  SHAMAN_RESTORATION   = 264,
  MAGE_ARCANE          = 62,
  MAGE_FIRE            = 63,
  MAGE_FROST           = 64,
  WARLOCK_AFFLICTION   = 265,
  WARLOCK_DEMONOLOGY   = 266,
  WARLOCK_DESTRUCTION  = 267,
  MONK_BREWMASTER      = 268,
  MONK_MISTWEAVER      = 270,
  MONK_WINDWALKER      = 269,
  DRUID_BALANCE        = 102,
  DRUID_FERAL          = 103,
  DRUID_GUARDIAN       = 104,
  DRUID_RESTORATION    = 105,
  PET_FEROCITY         = 74,
  PET_TENACITY         = 81,
  PET_CUNNING          = 79,
};

static specialization_t __class_spec_id[MAX_SPEC_CLASS][MAX_SPECS_PER_CLASS] = 
{
  {
    SPEC_NONE,
  },
  {
    WARRIOR_ARMS,
    WARRIOR_FURY,
    WARRIOR_PROTECTION,
    SPEC_NONE,
  },
  {
    PALADIN_HOLY,
    PALADIN_PROTECTION,
    PALADIN_RETRIBUTION,
    SPEC_NONE,
  },
  {
    HUNTER_BEAST_MASTERY,
    HUNTER_MARKSMANSHIP,
    HUNTER_SURVIVAL,
    SPEC_NONE,
  },
  {
    ROGUE_ASSASSINATION,
    ROGUE_COMBAT,
    ROGUE_SUBTLETY,
    SPEC_NONE,
  },
  {
    PRIEST_DISCIPLINE,
    PRIEST_HOLY,
    PRIEST_SHADOW,
    SPEC_NONE,
  },
  {
    DEATH_KNIGHT_BLOOD,
    DEATH_KNIGHT_FROST,
    DEATH_KNIGHT_UNHOLY,
    SPEC_NONE,
  },
  {
    SHAMAN_ELEMENTAL,
    SHAMAN_ENHANCEMENT,
    SHAMAN_RESTORATION,
    SPEC_NONE,
  },
  {
    MAGE_ARCANE,
    MAGE_FIRE,
    MAGE_FROST,
    SPEC_NONE,
  },
  {
    WARLOCK_AFFLICTION,
    WARLOCK_DEMONOLOGY,
    WARLOCK_DESTRUCTION,
    SPEC_NONE,
  },
  {
    MONK_BREWMASTER,
    MONK_MISTWEAVER,
    MONK_WINDWALKER,
    SPEC_NONE,
  },
  {
    DRUID_BALANCE,
    DRUID_FERAL,
    DRUID_GUARDIAN,
    DRUID_RESTORATION,
  },
  {
    PET_FEROCITY,
    PET_TENACITY,
    PET_CUNNING,
    SPEC_NONE,
  },
};


