[general]
output_base = ../engine/dbc/generated
output_base_txt = ../SpellDataDump
module_base = dbc.generator

[client_data_version.inc]
generators = ClientDataVersionGenerator

[sc_specialization_data.inc]
generators = SpecializationEnumGenerator

[sc_spec_list.inc]
generators = SpecializationListGenerator

[sc_spell_data.inc]
generators = SpellDataGenerator

[spell_id_list.txt]
generators = SpellIDListGenerator

[spelltext_data.inc]
generators = SpellTextGenerator
	SpellDescVarGenerator

[power_type_data.inc]
generators = PowerTypeGenerator

[racial_spells.inc]
generators = RacialSpellGenerator

[item_data.inc]
generators = ItemDataGenerator

[rand_prop_points.inc]
generators = RandomPropertyPointsGenerator

[item_effect.inc]
generators = ItemEffectGenerator

[spell_item_enchantment.inc]
generators = SpellItemEnchantmentGenerator

[item_armor.inc]
generators = ArmorValueDataGenerator
	ArmorLocationDataGenerator

[item_weapon.inc]
generators = WeaponDamageDataGenerator

[item_bonus.inc]
generators = ItemBonusDataGenerator

[item_scaling.inc]
generators = ScalingStatDataGenerator
	ItemScalingConfigGenerator
	ItemOffsetCurveGenerator

[content_tuning.inc]
generators = ContentTuningGenerator

[item_naming.inc]
generators = ItemNameDescriptionDataGenerator

[temporary_enchant.inc]
generators = TemporaryEnchantItemGenerator

[permanent_enchant.inc]
generators = PermanentEnchantItemGenerator
