[general]
output_base = ../engine/dbc/generated
output_base_txt = ../SpellDataDump
module_base = dbc.generator

[client_data_version.inc]
generators = ClientDataVersionGenerator

# [sc_specialization_data.inc] manually defined. TODO (forever): how does chrspecialization interact with other tables
# generators = SpecializationEnumGenerator

# [sc_spec_list.inc] manually defined.
# generators = SpecializationListGenerator

# [trait_data.inc] stubbed. TODO (forever): understand how trait trees are looked up
# generators = TraitGenerator

[sc_spell_data.inc]
generators = SpellDataGenerator

[spell_id_list.txt]
generators = SpellIDListGenerator

[spelltext_data.inc]
generators = SpellTextGenerator
	SpellDescVarGenerator

[power_type_data.inc]
generators = PowerTypeGenerator

[racial_spells.inc]
generators = RacialSpellGenerator

# [class_spells.inc] currently stubbed. TODO (forever): understanding how skill line works
# generators = ActiveClassSpellGenerator
# 	ActivePetSpellGenerator
# 	PassiveClassSpellGenerator

# [specialization_spells.inc] currently stubbed. unused.
# generators = SpecializationSpellGenerator

# [rank_spells.inc] currently stubbed. unused.
# generators = RankSpellGenerator

# [item_set_bonus.inc] currently stubbed, define sets in generator
# generators = SetBonusListGenerator

[item_data.inc]
generators = ItemDataGenerator

[rand_prop_points.inc]
generators = RandomPropertyPointsGenerator

[item_effect.inc]
generators = ItemEffectGenerator

[spell_item_enchantment.inc]
generators = SpellItemEnchantmentGenerator

[item_armor.inc]
generators = ArmorValueDataGenerator
	ArmorLocationDataGenerator

[item_weapon.inc]
generators = WeaponDamageDataGenerator

# [gem_data.inc] currently stubbed.
# generators = GemPropertyDataGenerator

[item_bonus.inc]
generators = ItemBonusDataGenerator

[item_scaling.inc]
generators = ScalingStatDataGenerator
	ItemScalingConfigGenerator
	ItemOffsetCurveGenerator

[content_tuning.inc]
generators = ContentTuningGenerator

[item_naming.inc]
generators = ItemNameDescriptionDataGenerator

# [item_child.inc] currently stubbed.
# generators = ItemChildEquipmentGenerator

[temporary_enchant.inc]
generators = TemporaryEnchantItemGenerator

[permanent_enchant.inc]
generators = PermanentEnchantItemGenerator

# doesn't provide any map-id correlation as i am unware of any strategy to correlate exists in current forever data
# sets id to 0
[expected_stat.inc]
generators = ExpectedStatGenerator
  ExpectedStatModGenerator

# [character_loadout.inc] stubbed.
# generators = CharacterLoadoutGenerator
# 	TraitLoadoutGenerator TODO (forever): understand how trait trees are looked up
