name: build

on:
  workflow_call:
    inputs:
      do-test:
        type: boolean
        required: true

jobs:
  ubuntu-gcc-build:
    name: ubuntu-${{ matrix.compiler }}-cpp${{ matrix.cppVersion }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [gcc-12, gcc-14]
        cppVersion: [17, 20]
        include:
          - compiler: gcc-12
            cxx: g++-12
            packages: gcc-12 g++-12
            os: ubuntu-22.04
          - compiler: gcc-14
            cxx: g++-14
            packages: gcc-14 g++-14
            os: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        env:
          CCACHE_PREFIX: "ubuntu-${{ matrix.compiler }}-cpp-${{ matrix.cppVersion }}-ccache-${{ env.CCACHE_GENERATION }}"
        with:
          path: ${{ runner.workspace }}/.ccache
          key: ${{ env.CCACHE_PREFIX }}-${{ github.sha }}
          restore-keys: ${{ env.CCACHE_PREFIX }}-

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev ninja-build ccache ${{ matrix.packages }}

      - name: Configure
        run:
          cmake -H. -B'${{ runner.workspace }}/b/ninja' -GNinja -DBUILD_GUI=OFF
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -DCMAKE_C_COMPILER=${{ matrix.compiler }}
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_STANDARD=${{ matrix.cppVersion }}

      - name: Build
        env:
          CCACHE_BASEDIR: ${{ runner.workspace }}
          CCACHE_DIR: ${{ runner.workspace }}/.ccache
          CCACHE_MAXSIZE: 350M
        run: |
          ccache -z
          ninja -C '${{ runner.workspace }}/b/ninja'
          ccache -s

      - uses: actions/cache@v5
        with:
          path: |
            ${{ runner.workspace }}/b/ninja/simc
            ActionPriorityLists
            profiles
            .git
          key: ubuntu-${{ matrix.compiler }}-for_run-${{ github.sha }}-cpp-${{ matrix.cppVersion }}

  ubuntu-clang-build:
    name: ubuntu-build-${{ matrix.compiler }}-C++${{ matrix.cppVersion }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cppVersion: [17, 20]
        compiler: [clang++-15, clang++-18]
        include:
          - compiler: clang++-15
            os: ubuntu-22.04
            packages: clang-15 lld-15
            enable_file_prefix_map: true
          - compiler: clang++-18
            os: ubuntu-24.04
            packages: clang-18 lld-18
            enable_file_prefix_map: true

    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        env:
          CCACHE_PREFIX: "ubuntu-${{ matrix.compiler }}-cpp-${{ matrix.cppVersion }}-ccache-${{ env.CCACHE_GENERATION }}"
        with:
          path: ${{ runner.workspace }}/.ccache
          key: ${{ env.CCACHE_PREFIX }}-${{ github.sha }}
          restore-keys: ${{ env.CCACHE_PREFIX }}-

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev ninja-build ccache ${{ matrix.packages }}

      - name: Configure
        env:
          UBSAN_STRIP_COUNT: '`echo "${{ runner.workspace }}//" | grep -o ''/'' - | wc -l`'
        run:
          cmake -H. -B'${{ runner.workspace }}/b/ninja' -GNinja -DBUILD_GUI=OFF
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
          -DCMAKE_CXX_FLAGS="-Og ${{ matrix.enable_file_prefix_map && format('-ffile-prefix-map={0}/=/', runner.workspace) || ''}}
          -fno-omit-frame-pointer -fsanitize=address,undefined
          -fsanitize-undefined-strip-path-components=$UBSAN_STRIP_COUNT"
          -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -fsanitize=address,undefined"
          -DCMAKE_CXX_STANDARD=${{ matrix.cppVersion }}
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        env:
          CCACHE_BASEDIR: ${{ runner.workspace }}
          CCACHE_DIR: ${{ runner.workspace }}/.ccache
          CCACHE_MAXSIZE: 400M
        run: |
          ccache -z
          ninja -C '${{ runner.workspace }}/b/ninja'
          ccache -s

      - uses: actions/cache@v5
        with:
          path: |
            ${{ runner.workspace }}/b/ninja/simc
            ActionPriorityLists
            profiles
            .git
          key: ubuntu-${{ matrix.compiler }}-for_run-${{ github.sha }}-cpp-${{ matrix.cppVersion }}

  build-osx:
    name: macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        env:
          CCACHE_PREFIX: "macos-cpp-ccache-${{ env.CCACHE_GENERATION }}"
        with:
          path: ${{ runner.workspace }}/.ccache
          key: ${{ env.CCACHE_PREFIX }}-${{ github.sha }}
          restore-keys: ${{ env.CCACHE_PREFIX }}-

      - name: Install deps
        run: |
          brew update
          brew install ccache

      - name: Build
        env:
          CCACHE_BASEDIR: ${{ runner.workspace }}
          CCACHE_DIR: ${{ runner.workspace }}/.ccache
          CCACHE_MAXSIZE: 500M
        run: |
          ccache -z
          make CXX="ccache c++" SANITIZE=1 -C engine debug -j 2
          ccache -s

  windows-VS:
    name: windows-VS-${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, amd64_arm64]

    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/builddir/

    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        env:
          CCACHE_PREFIX: "windows-${{ matrix.arch }}-cpp-ccache-${{ env.CCACHE_GENERATION }}"
        with:
          path: ${{ github.workspace }}\.ccache
          key: ${{ env.CCACHE_PREFIX }}-${{ github.sha }}
          restore-keys: ${{ env.CCACHE_PREFIX }}-

      # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly. As used here the Developer Command Prompt created is targeting x64 and using the default the Windows SDK.
      - uses: step-security/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Install deps
        run: |
          choco install -y ccache

      - name: Generate project files
        run: |
          cmake -B "${{ env.CMAKE_BUILD_DIR }}" `
            -GNinja `
            -DBUILD_GUI=OFF `
            -DCMAKE_BUILD_TYPE=Debug `
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache `
            -DCMAKE_CXX_FLAGS_DEBUG="/Z7"

      - name: Build
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}\.ccache
          CCACHE_MAXSIZE: 400M
        run: |
          ccache -z
          cmake --build "${{ env.CMAKE_BUILD_DIR }}"
          ccache -s
