name: build

on:
  workflow_call:
    inputs:
      do-test:
        type: boolean
        required: true

jobs:
  ubuntu-clang-build:
    name: ubuntu-build-${{ matrix.compiler }}-C++${{ matrix.cppVersion }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cppVersion: [17]
        compiler: [clang++-15]
        include:
          - compiler: clang++-15
            os: ubuntu-22.04
            packages: clang-15 lld-15
            enable_file_prefix_map: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        env:
          CCACHE_PREFIX: "ubuntu-${{ matrix.compiler }}-cpp-${{ matrix.cppVersion }}-ccache-${{ env.CCACHE_GENERATION }}"
        with:
          path: ${{ runner.workspace }}/.ccache
          key: ${{ env.CCACHE_PREFIX }}-${{ github.sha }}
          restore-keys: ${{ env.CCACHE_PREFIX }}-

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev ninja-build ccache ${{ matrix.packages }}

      - name: Configure
        env:
          UBSAN_STRIP_COUNT: '`echo "${{ runner.workspace }}//" | grep -o ''/'' - | wc -l`'
        run:
          cmake -H. -B'${{ runner.workspace }}/b/ninja' -GNinja -DBUILD_GUI=OFF
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
          -DCMAKE_CXX_FLAGS="-Og ${{ matrix.enable_file_prefix_map && format('-ffile-prefix-map={0}/=/', runner.workspace) || ''}}
          -fno-omit-frame-pointer -fsanitize=thread,undefined
          -fsanitize-undefined-strip-path-components=$UBSAN_STRIP_COUNT"
          -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -fsanitize=address,undefined"
          -DCMAKE_CXX_STANDARD=${{ matrix.cppVersion }}
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        env:
          CCACHE_BASEDIR: ${{ runner.workspace }}
          CCACHE_DIR: ${{ runner.workspace }}/.ccache
          CCACHE_MAXSIZE: 256M # full build consumes around ~124, ~2x that to be safe
        run: |
          ccache -z
          ninja -C '${{ runner.workspace }}/b/ninja'
          ccache -s

      - uses: actions/cache@v4
        with:
          path: |
            ${{ runner.workspace }}/b/ninja/simc
            profiles
            tests
            generate_profiles_ci.sh
            .git
          key: ubuntu-${{ matrix.compiler }}-for_run-${{ github.sha }}-cpp-${{ matrix.cppVersion }}
