name: CI

on:
  pull_request:
    branches: [thewarwithin, midnight]
  push:
    branches: [thewarwithin, midnight]
    paths-ignore:
      - "ActionPriorityLists/**"
      - "SpellDataDump/*.txt"
      - "dbc_extract3/**"
      - "casc_extract/**"

env:
  SIMC_PROFILE: profiles/CI.simc
  CCACHE_GENERATION: 0 # bump if you need to "clean" ccache

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      do-test: ${{ github.base_ref == github.event.repository.default_branchy || github.base_ref == 'midnight' }}

  environment-configuration-info:
    runs-on: ubuntu-22.04
    steps:
      - name: Report Environment Configuration Information
        run: |
          echo "${{github.event.repository.default_branch}} ${{github.base_ref}} ${{github.sha}}"

  spec-test:
    needs: [build]
    if: github.base_ref == github.event.repository.default_branch || github.base_ref == 'midnight'
    uses: ./.github/workflows/spec_test.yml
    with:
      cache-key: ubuntu-clang++-15-for_run-${{ github.sha }}-cpp-17
      is-ptr: false

  spec-test-ptr:
    needs: [build]
    if: github.base_ref == github.event.repository.default_branch
    uses: ./.github/workflows/spec_test.yml
    with:
      cache-key: ubuntu-clang++-15-for_run-${{ github.sha }}-cpp-17
      is-ptr: true

  ubuntu-test:
    needs: [build]
    if: github.base_ref == github.event.repository.default_branch || github.base_ref == 'midnight'
    uses: ./.github/workflows/ubuntu_test.yml

  # this job will do bad things if enabled for non-default branch without additional work
  update-generated-files:
    needs: [build, spec-test]
    if: github.event_name == 'push' && ( success() || failure() ) && github.repository == 'simulationcraft/simc' && github.base_ref == github.event.repository.default_branch
    uses: ./.github/workflows/generate_files.yml
