name: spec-test

on:
  workflow_call:
    inputs:
      cache-key:
        type: string
        required: true
      is-ptr:
        type: boolean
        required: true
      spec-matrix:
        type: string
        required: true

jobs:
  spec-test:
    name: spec-test-${{ matrix.spec }}
    runs-on: ubuntu-22.04
    continue-on-error: ${{ inputs.is-ptr }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(inputs.spec-matrix) }}

    env:
      UBSAN_OPTIONS: print_stacktrace=1
      SIMC_ARGS: output=/dev/null threads=4 profileset_work_threads=2 iterations=10 cleanup_threads=1 allow_experimental_specializations=1
      PLAYER_ARGS: load_default_gear=1
      MT_ARGS: desired_targets=10 max_time=60
      DS_ARGS: fight_style=DungeonSlice

    steps:
      - uses: actions/cache@v5
        with:
          path: |
            ${{ runner.workspace }}/b/ninja/simc
            ActionPriorityLists
            profiles
            .git
          key: ${{ inputs.cache-key }}

      - name: Setup
        id: setup
        env:
          MATRIX_SPEC: ${{ matrix.spec }}
        run: |
          CLASS_STR=${MATRIX_SPEC%%_*}
          CLASS_STR_CAP=${CLASS_STR^}
          SPEC_STR=${MATRIX_SPEC#*_}
          echo "CLASS_STR=$CLASS_STR" >> "$GITHUB_ENV"
          echo "CLASS_STR_CAP=$CLASS_STR_CAP" >> "$GITHUB_ENV"
          echo "SPEC_STR=$SPEC_STR" >> "$GITHUB_ENV"

      - name: Enable PTR
        if: inputs.is-ptr
        run: echo "PTR_ARG=ptr=1" >> "$GITHUB_ENV"

      - name: "Assisted Combat Validation"
        run: |
          SECONDS=0
          echo ">>>>> Hero Tree 1 <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} iterations=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1 set_bonus=latest_2pc=1/latest_4pc=1 use_blizzard_action_list=1
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Hero Tree 2 <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} iterations=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2 set_bonus=latest_2pc=1/latest_4pc=1 use_blizzard_action_list=1
          echo "Run time: $SECONDS seconds"

      - name: "Log Debug"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} log=1 debug=1 \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"

      - name: "HTML JSON"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Single Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} html=test.html json=test.json \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Multi Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} html=test_mt.html json=test_mt.json \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} html=test_ds.html json=test_ds.json \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"

      - name: "No Talents, No Effects, No Sets"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Single Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Multi Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          SECONDS=0

      - name: "No Talents, No Effects, All Sets"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Single Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Multi Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"

      - name: "No Talents, All Effects, No Sets"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Single Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_item_effects=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Multi Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_item_effects=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_item_effects=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"

      - name: "All Talents, No Effects, No Sets"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Single Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_talents=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Multi Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_talents=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_talents=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"

      - name: "Starter Talents, Hero Tree 1, No Sets"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Single Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Multi Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1
          echo "Run time: $SECONDS seconds"

      - name: "Starter Talents, Hero Tree 2, No Sets"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Single Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Multi Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2
          echo "Run time: $SECONDS seconds"

      - name: "Starter Talents, Hero Tree 1, All Sets"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Single Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Multi Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1
          echo "Run time: $SECONDS seconds"

      - name: "Starter Talents, Hero Tree 2, All Sets"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Single Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Multi Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2
          echo "Run time: $SECONDS seconds"

      - name: "All Talents, All Effects, All Sets"
        if: always()
        run: |
          SECONDS=0
          echo ">>>>> Single Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Multi Target <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"
          SECONDS=0
          echo ">>>>> Dungeon Slice <<<<<"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo "Run time: $SECONDS seconds"

      - name: "Profileset Test"
        if: always()
        run: |
          SECONDS=0
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            profileset.base=load_default_talents=1 \
            profileset.one=load_default_talents=1 profileset.one+=hero_talents=1 \
            profileset.two=load_default_talents=1 profileset.two+=hero_talents=2 \
            profileset.one_2pc=load_default_talents=1 profileset.one_2pc+=hero_talents=1 \
            profileset.one_2pc+=set_bonus=latest_2pc=1 \
            profileset.two_2pc=load_default_talents=1 profileset.two_2pc+=hero_talents=2 \
            profileset.two_2pc+=set_bonus=latest_2pc=1 \
            profileset.one_4pc=load_default_talents=1 profileset.one_4pc+=hero_talents=1 \
            profileset.one_4pc+=set_bonus=latest_2pc=1 profileset.one_4pc+=set_bonus+=/latest_4pc=1 \
            profileset.two_4pc=load_default_talents=1 profileset.two_4pc+=hero_talents=2 \
            profileset.two_4pc+=set_bonus=latest_2pc=1 profileset.two_4pc+=set_bonus+=/latest_4pc=1
          echo "Run time: $SECONDS seconds"

      - name: Dump APL Default
        id: dump_apl_default
        if: github.event_name == 'push' && !failure() && !inputs.is-ptr
        run: |
          ${{ runner.workspace }}/b/ninja/simc save_profiles=1 save_full_profile=0 \
            enable_all_talents=1 enable_all_sets=1 \
            allow_experimental_specializations=1  ${{ env.CLASS_STR }}=${{ matrix.spec }} \
            spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            save_actions=ActionPriorityLists/default/${{ matrix.spec }}.simc

      - name: Dump APL Assisted
        id: dump_apl_assisted
        if: github.event_name == 'push' && !failure() && !inputs.is-ptr
        run: |
          ${{ runner.workspace }}/b/ninja/simc save_profiles=1 save_full_profile=0 \
            enable_all_talents=1 enable_all_sets=1 \
            allow_experimental_specializations=1  ${{ env.CLASS_STR }}=${{ matrix.spec }} \
            spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} use_blizzard_action_list=1 \
            save_actions=ActionPriorityLists/assisted_combat/${{ matrix.spec }}.simc

      - name: Check APL Changes
        id: check_apl_changes
        if: (steps.dump_apl_default.outcome == 'success' || steps.dump_apl_assisted.outcome == 'success')
        shell: bash
        run: |
          CHANGED=$(git status --porcelain -- \
            ActionPriorityLists/default/${{ matrix.spec }}.simc \
            ActionPriorityLists/assisted_combat/${{ matrix.spec }}.simc)
          if [ -n "$CHANGED" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload APL
        if: steps.check_apl_changes.outputs.changed == 'true'
        continue-on-error: true
        uses: actions/upload-artifact@v6
        with:
          name: apl-${{ github.sha }}-${{ matrix.spec }}
          path: |
            ActionPriorityLists/*/${{ matrix.spec }}.simc
          retention-days: 1

      - name: Generate Profiles
        id: generate_profiles
        if: github.event_name == 'push' && !failure() && !inputs.is-ptr
        continue-on-error: true
        shell: bash
        run: |
          cd profiles
          for dir in generators/*; do
            if [ -d $dir ]; then
              SEASON=${dir##*/}
              GENERATOR=${SEASON}_Generate_${{ env.CLASS_STR_CAP }}.simc
              if [ -f $dir/$GENERATOR ]; then
                cd $SEASON
                echo "---$SEASON---${{ env.CLASS_STR_CAP }}---$GENERATOR---"
                ${{ runner.workspace }}/b/ninja/simc $dir/$GENERATOR
                cd ..
              fi
            fi
          done

      - name: Check Profile Changes
        id: check_profile_changes
        if: steps.generate_profiles.outcome == 'success'
        continue-on-error: true
        shell: bash
        run: |
          CHANGED=$(git status --porcelain -- profiles/*/*.simc | sed 's/^...//')
          if [ -n "$CHANGED" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "Changed profile files:"
            echo "$CHANGED"
            mkdir -p /tmp/changed_profiles
            echo "$CHANGED" | while read -r f; do
              cp --parents "$f" /tmp/changed_profiles/
            done
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No profile files changed"
          fi

      - name: Upload Profiles
        if: steps.check_profile_changes.outputs.changed == 'true'
        continue-on-error: true
        uses: actions/upload-artifact@v6
        with:
          name: profiles-${{ github.sha }}-${{ matrix.spec }}
          path: /tmp/changed_profiles/profiles/
          retention-days: 1
