name: spec-test

on:
  workflow_call:
    inputs:
      cache-key:
        type: string
        required: true
      is-ptr:
        type: boolean
        required: true
      spec-matrix:
        type: string
        required: true

jobs:
  spec-test:
    name: spec-test-${{ matrix.spec }}
    runs-on: ubuntu-22.04
    continue-on-error: ${{ inputs.is-ptr }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(inputs.spec-matrix) }}

    env:
      UBSAN_OPTIONS: print_stacktrace=1
      SIMC_ARGS: output=/dev/null threads=4 profileset_work_threads=2 iterations=10 cleanup_threads=1 allow_experimental_specializations=1
      PLAYER_ARGS: load_default_gear=1
      MT_ARGS: desired_targets=10
      DS_ARGS: fight_style=DungeonSlice

    steps:
      - uses: actions/cache@v5
        with:
          path: |
            ${{ runner.workspace }}/b/ninja/simc
            profiles
            tests
            generate_profiles_ci.sh
            .git
          key: ${{ inputs.cache-key }}

      - name: Setup
        id: setup
        env:
          MATRIX_SPEC: ${{ matrix.spec }}
        run: |
          echo "CLASS_STR=${MATRIX_SPEC%%_*}" >> "$GITHUB_ENV"
          echo "SPEC_STR=${MATRIX_SPEC#*_}" >> "$GITHUB_ENV"

      - name: Enable PTR
        if: inputs.is-ptr
        run: echo "PTR_ARG=ptr=1" >> "$GITHUB_ENV"

      - name: "Assisted Combat Validation"
        run: |
          echo ">>>>> Hero Tree 1 <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} iterations=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1 set_bonus=latest_2pc=1/latest_4pc=1 use_blizzard_action_list=1
          echo
          echo ">>>>> Hero Tree 2 <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} iterations=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2 set_bonus=latest_2pc=1/latest_4pc=1 use_blizzard_action_list=1

      - name: "Log Debug"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} log=1 debug=1 \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} log=1 debug=1 \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} log=1 debug=1 \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}

      - name: "HTML JSON"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} html=test.html json=test.json \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} html=test_mt.html json=test_mt.json \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} html=test_ds.html json=test_ds.json \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}

      - name: "No Talents, No Effects, No Sets"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}

      - name: "No Talents, No Effects, All Sets"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}

      - name: "No Talents, All Effects, No Sets"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_item_effects=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_item_effects=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_item_effects=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}

      - name: "All Talents, No Effects, No Sets"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_talents=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_talents=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_talents=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}

      - name: "Starter Talents, Hero Tree 1, No Sets"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1

      - name: "Starter Talents, Hero Tree 2, No Sets"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2

      - name: "Starter Talents, Hero Tree 1, All Sets"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=1

      - name: "Starter Talents, Hero Tree 2, All Sets"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            load_default_talents=1 hero_talents=2

      - name: "All Talents, All Effects, All Sets"
        if: always()
        run: |
          echo ">>>>> Single Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Multi Target <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.MT_ARGS}} \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}
          echo
          echo ">>>>> Dungeon Slice <<<<< $(date +%T)"
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} ${{ env.DS_ARGS}} \
            enable_all_talents=1 enable_all_item_effects=1 enable_all_sets=1 \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }}

      - name: "Profileset Test"
        if: always()
        run: |
          ${{ runner.workspace }}/b/ninja/simc ${{ env.PTR_ARG }} ${{ env.SIMC_ARGS }} \
            ${{ env.CLASS_STR }}=${{ matrix.spec }} spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            profileset.base=load_default_talents=1 \
            profileset.one=load_default_talents=1 profileset.one+=hero_talents=1 \
            profileset.two=load_default_talents=1 profileset.two+=hero_talents=2 \
            profileset.one_2pc=load_default_talents=1 profileset.one_2pc+=hero_talents=1 \
            profileset.one_2pc+=set_bonus=latest_2pc=1 \
            profileset.two_2pc=load_default_talents=1 profileset.two_2pc+=hero_talents=2 \
            profileset.two_2pc+=set_bonus=latest_2pc=1 \
            profileset.one_4pc=load_default_talents=1 profileset.one_4pc+=hero_talents=1 \
            profileset.one_4pc+=set_bonus=latest_2pc=1 profileset.one_4pc+=set_bonus+=/latest_4pc=1 \
            profileset.two_4pc=load_default_talents=1 profileset.two_4pc+=hero_talents=2 \
            profileset.two_4pc+=set_bonus=latest_2pc=1 profileset.two_4pc+=set_bonus+=/latest_4pc=1

      - name: Dump APL Default
        id: dump_apl_default
        if: github.event_name == 'push' && !failure() && !inputs.is-ptr
        run: |
          mkdir default
          ${{ runner.workspace }}/b/ninja/simc save_profiles=1 save_full_profile=0 \
            enable_all_talents=1 enable_all_sets=1 \
            allow_experimental_specializations=1  ${{ env.CLASS_STR }}=${{ matrix.spec }} \
            spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} \
            save_actions=default/${{ matrix.spec }}.simc

      - name: Dump APL Assisted
        id: dump_apl_assisted
        if: github.event_name == 'push' && !failure() && !inputs.is-ptr
        run: |
          mkdir assisted_combat
          ${{ runner.workspace }}/b/ninja/simc save_profiles=1 save_full_profile=0 \
            enable_all_talents=1 enable_all_sets=1 \
            allow_experimental_specializations=1  ${{ env.CLASS_STR }}=${{ matrix.spec }} \
            spec=${{ env.SPEC_STR }} ${{ env.PLAYER_ARGS }} use_blizzard_action_list=1 \
            save_actions=assisted_combat/${{ matrix.spec }}.simc

      - name: Upload APL
        if: steps.dump_apl_default.outcome == 'success' || steps.dump_apl_assisted.outcome == 'success'
        continue-on-error: true
        uses: actions/upload-artifact@v6
        with:
          name: apl-${{ github.sha }}-${{ matrix.spec }}
          path: |
            default/${{ matrix.spec }}.simc
            assisted_combat/${{ matrix.spec }}.simc
          retention-days: 1
