name: ubuntu-run

on:
  workflow_call:
    inputs:
      cache-sha:
        type: string
        required: true

env:
  SIMC_PROFILE: profiles/CI.simc

jobs:
  ubuntu-run:
    name: ubuntu-${{ matrix.compiler }}-cpp-${{ matrix.cppVersion }}-${{ matrix.type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        cppVersion: [17, 20]
        compiler: [clang++-15, clang++-18, gcc-12, gcc-14]
        type: [spell_query, log_debug, patchwerk, dungeon_slice]
        include:
          - type: spell_query
            simc_flags: spell_query=spell > /dev/null
          - type: log_debug
            simc_flags: $SIMC_PROFILE log=1 debug=1 max_time=100
          - type: patchwerk
            simc_flags: $SIMC_PROFILE iterations=10 cleanup_threads=1
          - type: dungeon_slice
            simc_flags: $SIMC_PROFILE iterations=10 fight_style=DungeonSlice allow_experimental_specializations=1 cleanup_threads=1
          - compiler: clang++-15
            os: ubuntu-22.04
          - compiler: clang++-18
            os: ubuntu-24.04
          - compiler: gcc-14
            os: ubuntu-24.04
          - compiler: gcc-12
            os: ubuntu-22.04

    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ${{ runner.workspace }}/b/ninja/simc
            profiles
            tests
            generate_profiles_ci.sh
            .git
          key: ubuntu-${{ matrix.compiler }}-for_run-${{ inputs.cache-sha }}-cpp-${{ matrix.cppVersion }}

      - name: Run
        env:
          UBSAN_OPTIONS: print_stacktrace=1
        run: ${{ runner.workspace }}/b/ninja/simc output=/dev/null html=/dev/null json2=/dev/null ${{ matrix.simc_flags }}
