name: ubuntu-test

on:
  workflow_call:

env:
  SIMC_PROFILE: profiles/CI.simc
  SIMC_ARGS: output=/dev/null html=/dev/null json=/dev/null

jobs:
  ubuntu-test:
    name: ubuntu-${{ matrix.compiler }}-cpp-${{ matrix.cppVersion }}-${{ matrix.type }}
    runs-on: ${{ matrix.os }}
    env:
      CACHE_KEY: ubuntu-${{ matrix.compiler }}-for_run-${{ github.sha }}-cpp-${{ matrix.cppVersion }}
      UBSAN_OPTIONS: print_stacktrace=1

    strategy:
      fail-fast: false
      matrix:
        cppVersion: [17, 20]
        compiler: [clang++-15, clang++-18, gcc-12, gcc-14]
        include:
          - compiler: clang++-15
            os: ubuntu-22.04
          - compiler: clang++-18
            os: ubuntu-24.04
          - compiler: gcc-14
            os: ubuntu-24.04
          - compiler: gcc-12
            os: ubuntu-22.04

    steps:
      - uses: actions/cache@v5
        with:
          path: |
            ${{ runner.workspace }}/b/ninja/simc
            ActionPriorityLists
            profiles
            .git
          key: ${{ env.CACHE_KEY }}

      - name: "Spell Query"
        run: ${{ runner.workspace }}/b/ninja/simc $SIMC_ARGS spell_query=spell > /dev/null

      - name: "Patchwerk"
        run: ${{ runner.workspace }}/b/ninja/simc $SIMC_ARGS $SIMC_PROFILE iterations=10 cleanup_threads=1

      - name: "DungeonSlice"
        run: ${{ runner.workspace }}/b/ninja/simc $SIMC_ARGS $SIMC_PROFILE iterations=10 fight_style=DungeonSlice allow_experimental_specializations=1 cleanup_threads=1

      - name: Clear Cache
        if: ( matrix.compiler != 'clang++-15' || matrix.cppVersion != '17' ) && github.event_name == 'push'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh cache delete ${{ env.CACHE_KEY }}
